
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_dwh_farinter'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_dwh_farinter'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models","groups"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.


models:
  dbt_dwh_farinter:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
      +group: "dbt_first_group"
    dagster_example:
      +group: "dbt_second_group_test"
    dwh_sap:
      mart_datos_maestros:
        +group: "dbt_dwh_sap_mart_datos_maestros"
      mart_finanzas:
        +group: "dbt_dwh_sap_mart_finanzas"
      sap_etl_datos_maestros:
        +group: "sap_etl_dwh"
        +database: "DL_FARINTER"
       
    dwh_kielsa:
#      mart_finanzas:
#        +group: "dbt_dwh_kielsa_mart_finanzas"
      mart_datos_maestros:
        +group: "dbt_dwh_kielsa_mart_datos_maestros"
        +meta:
            dagster:
                group: "dbt_dwh_kielsa_mart_datos_maestros"
      mart_kpp:
        +group: 'dbt_dwh_kielsa_mart_kpp'
        +meta:
            dagster:
                group: 'dbt_dwh_kielsa_mart_kpp'


sources:
  dbt_dwh_farinter:
    dwh_kielsa:
      mart_datos_maestros:
        +group: 'ldcom_etl_dwh'
      mart_kpp:
        +group: 'dbt_dwh_kielsa_mart_kpp'
    dwh_sap:
      mart_finanzas:
        +group: 'sap_etl_dwh'
      sap_etl_datos_maestros:
        +group: 'sap_prd'
#    marts:
#      +group: "marts_group"
#      mart1:
#        +group: "mart1_group"
#      mart2:
#       +group: "mart2_group"
#  +post_hook:    "{{dwh_farinter_create_primary_key(this,columns=['Sociedad_Id'], create_clustered=True, is_incremental=0,if_another_exists_delete=True, show_info=True)}}"


vars:
  P_SAPPRD_LS: SAPPRD #Linked server de SAP PRD
  P_SQLLDSUBS_LS: REPLICASLD #Linked server de Replicas de KIelsa, SITEPLUS y otros



