
version: 1

models:
  - name: BI_SAP_Dim_CuentaContable
    description: "Cuentas contables"
    #config: #no implementado en dbt-sqlserver
      #constraints_enabled: true
    columns:
      - name: PlanCuentas_Id
        description: "Diversas estructuras de cuentas, posible una diferente por empresa."
        #constraint: not_null

      - name: Cuenta_Id
        description: "Cuenta contable"
        #constraint: not_null

      - name: HashStr_PlanCuenta
        description: "Hash UNICO de la cuenta contable"
        #data_tests: #lleva indice
          #- unique
          #- not_null
  - name: BI_SAP_Dim_CuentaContableSociedad
    description: "Cuentas contables por sociedad"
    #config: #no implementado en dbt-sqlserver
      #constraints_enabled: true
    columns:
      - name: Sociedad_Id
      - name: Cuenta_Id
