# put your secret values and credentials here. do not share this file and do not push it to github
[sources.mongodb]
connection_url = "connection_url" # please set me up!

[destination.mssql.credentials]
database = "database" # please set me up!
password = "password" # please set me up!
username = "username" # please set me up!
host = "host" # please set me up!
port = 1433
connect_timeout = 15
driver = "driver" # please set me up!
