[pytest]
filterwarnings =
    ignore:.*'soft_unicode' has been renamed to 'soft_str'*:DeprecationWarning
    ignore:unclosed file .*:ResourceWarning
    ignore::DeprecationWarning:.*Pydantic V1 style `@validator` validators are deprecated..*

; env_files =
;     .env
testpaths =
    dagster_shared_gf/dagster_shared_gf_tests
    dagster_sap_gf/dagster_sap_gf_tests
    dagster_kielsa_gf/dagster_kielsa_gf_tests
; markers =
;     skip_profile
;     only_with_profile

