	--DROP TABLE IF EXISTS [DL_SAP_BSEG]
USE [DL_FARINTER]
GO
IF OBJECT_ID('[dbo].[DL_SAP_BSEG]', 'U') IS NULL
BEGIN

	IF EXISTS (SELECT *
		FROM sys.partition_schemes WHERE name = 'ps_DL_SAP_BSEG_AnioMes') 
		DROP PARTITION SCHEME ps_DL_SAP_BSEG_AnioMes
		;
	--Drop si existe function
	IF EXISTS (SELECT *
		FROM sys.partition_functions WHERE name = 'pf_DL_SAP_BSEG_AnioMes') 
		DROP PARTITION FUNCTION pf_DL_SAP_BSEG_AnioMes
		;

	CREATE PARTITION FUNCTION pf_DL_SAP_BSEG_AnioMes (INT) AS RANGE RIGHT FOR VALUES (201101);
	CREATE PARTITION SCHEME ps_DL_SAP_BSEG_AnioMes
	AS PARTITION pf_DL_SAP_BSEG_AnioMes
	ALL TO ([PRIMARY]);

	--Generar particiones en periodos anio a anio en la columna aniomes_id
	DECLARE
		@mensaje	NVARCHAR(4000), @PaqueteId NVARCHAR(1)	= '', @Tabla NVARCHAR(1) = 'DL_SAP_BSEG';
	DECLARE @limiteSiguienteFechas AS DATE = '2011-01-01';
	DECLARE @limiteSiguienteAnioMes INT;

    EXEC sp_UtilAgregarParticionSiguienteAnioMes @p_NombreTabla = @Tabla, @p_PeriodoTipo = 'Mensual', @p_FechaBase = @limiteSiguienteFechas, @p_NombreSchema = 'ps_DL_SAP_BSEG_AnioMes'

	--Verificar particiones
	SELECT     spf.name AS PartitionFunction,
		sprv.value AS RangeValue,
		sprv.boundary_id, spf.[type] AS PartitionFunctionType 	
	FROM 
		sys.partition_range_values sprv
	JOIN 
		sys.partition_functions spf 
		ON sprv.function_id = spf.function_id
	WHERE 
		spf.name = 'pf_DL_SAP_BSEG_AnioMes'


	--DROP TABLE IF EXISTS [DL_SAP_BSEG]

	CREATE TABLE [DL_SAP_BSEG] ( 
		[AnioMes_Id] INT NOT NULL  --  X-Anio y mes- YYYYMM INT 
		, [CPUDT] VARCHAR(8)  NOT NULL  --  -Fecha de registro-Check: -Datatype:DATS-Len:(8,0)
		, [AEDAT] VARCHAR(8)  NOT NULL  --  -Fecha de actualización-Check: -Datatype:DATS-Len:(8,0)
		, [BUKRS] VARCHAR(4)  NOT NULL  -- X-Sociedad-Check:T001-Datatype:CHAR-Len:(4,0)
		, [BELNR] VARCHAR(10)  NOT NULL  -- X-Número de un documento contable-Check: -Datatype:CHAR-Len:(10,0)
		, [GJAHR] VARCHAR(4)  NOT NULL  -- X-Ejercicio-Check: -Datatype:NUMC-Len:(4,0)
		, [BUZEI] VARCHAR(3)  NOT NULL  -- X-Número del apunte contable dentro del documento contable-Check: -Datatype:NUMC-Len:(3,0)
		, [BUZID] VARCHAR(1)  NOT NULL  --  -Identificación del apunte-Check: -Datatype:CHAR-Len:(1,0)
		, [AUGDT] VARCHAR(8)  NOT NULL  --  -Fecha de la compensación-Check: -Datatype:DATS-Len:(8,0)
		, [AUGCP] VARCHAR(8)  NOT NULL  --  -Día de registro de la compensación-Check: -Datatype:DATS-Len:(8,0)
		, [AUGBL] VARCHAR(10)  NOT NULL  --  -Número del documento de compensación-Check: -Datatype:CHAR-Len:(10,0)
		, [BSCHL] VARCHAR(2)  NOT NULL  --  -Clave de contabilización-Check:TBSL-Datatype:CHAR-Len:(2,0)
		, [KOART] VARCHAR(1)  NOT NULL  --  -Clase de cuenta-Check: -Datatype:CHAR-Len:(1,0)
		, [UMSKZ] VARCHAR(1)  NOT NULL  --  -Indicador de operación en cuenta de mayor especial-Check:T074U-Datatype:CHAR-Len:(1,0)
		, [UMSKS] VARCHAR(1)  NOT NULL  --  -Clase de operación en cuenta de mayor especial-Check: -Datatype:CHAR-Len:(1,0)
		, [ZUMSK] VARCHAR(1)  NOT NULL  --  -Indicador CME de destino-Check:T074U-Datatype:CHAR-Len:(1,0)
		, [SHKZG] VARCHAR(1)  NOT NULL  --  -Indicador debe/haber-Check: -Datatype:CHAR-Len:(1,0)
		, [GSBER] VARCHAR(4)  NOT NULL  --  -División-Check:TGSB-Datatype:CHAR-Len:(4,0)
		, [PARGB] VARCHAR(4)  NOT NULL  --  -División del interlocutor comercial-Check:TGSB-Datatype:CHAR-Len:(4,0)
		, [MWSKZ] VARCHAR(2)  NOT NULL  --  -Indicador IVA-Check:T007A-Datatype:CHAR-Len:(2,0)
		, [QSSKZ] VARCHAR(2)  NOT NULL  --  -Indicador de retención-Check:T059Q-Datatype:CHAR-Len:(2,0)
		, [DMBTR] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [WRBTR] DECIMAL(16,4)  NOT NULL  --  -Importe en la moneda del documento-Check: -Datatype:CURR-Len:(13,2)
		, [KZBTR] DECIMAL(16,4)  NOT NULL  --  -Importe de reducción original en moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [PSWBT] DECIMAL(16,4)  NOT NULL  --  -Importe de actualización en el libro mayor-Check: -Datatype:CURR-Len:(13,2)
		, [PSWSL] VARCHAR(5)  NOT NULL  --  -Moneda actualización para cifras movimientos libro mayor-Check:TCURC-Datatype:CUKY-Len:(5,0)
		, [TXBHW] DECIMAL(16,4)  NOT NULL  --  -Base imponible original en moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [TXBFW] DECIMAL(16,4)  NOT NULL  --  -Base imponible original en moneda del documento-Check: -Datatype:CURR-Len:(13,2)
		, [MWSTS] DECIMAL(16,4)  NOT NULL  --  -Importe del impuesto en moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [WMWST] DECIMAL(16,4)  NOT NULL  --  -Importe del impuesto en moneda del documento-Check: -Datatype:CURR-Len:(13,2)
		, [HWBAS] DECIMAL(16,4)  NOT NULL  --  -Importe base del impuesto en moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [FWBAS] DECIMAL(16,4)  NOT NULL  --  -Importe base impuesto moneda documento-Check: -Datatype:CURR-Len:(13,2)
		, [HWZUZ] DECIMAL(16,4)  NOT NULL  --  -Importe de provisión en moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [FWZUZ] DECIMAL(16,4)  NOT NULL  --  -Impuesto adicional en moneda del documento-Check: -Datatype:CURR-Len:(13,2)
		, [SHZUZ] VARCHAR(1)  NOT NULL  --  -Dato adicional Debe/Haber para descuento-Check: -Datatype:CHAR-Len:(1,0)
		, [STEKZ] VARCHAR(2)  NOT NULL  --  -Componente del número de versión-Check: -Datatype:CHAR-Len:(2,0)
		, [MWART] VARCHAR(1)  NOT NULL  --  -Clase de impuesto-Check: -Datatype:CHAR-Len:(1,0)
		, [TXGRP] VARCHAR(3)  NOT NULL  --  -Indicador de grupo para documentos de impuesto-Check: -Datatype:NUMC-Len:(3,0)
		, [KTOSL] VARCHAR(3)  NOT NULL  --  -Clave de operación-Check: -Datatype:CHAR-Len:(3,0)
		, [QSSHB] DECIMAL(16,4)  NOT NULL  --  -Importe base para retención-Check: -Datatype:CURR-Len:(13,2)
		, [KURSR] DECIMAL(16,4)  NOT NULL  --  -Tipo de cambio asegurado-Check: -Datatype:DEC-Len:(9,5)
		, [GBETR] DECIMAL(16,4)  NOT NULL  --  -Importe con tipo de cambio asegurado en moneda extranjera-Check: -Datatype:CURR-Len:(13,2)
		, [BDIFF] DECIMAL(16,4)  NOT NULL  --  -Diferencia de valoración-Check: -Datatype:CURR-Len:(13,2)
		, [BDIF2] DECIMAL(16,4)  NOT NULL  --  -Diferencia de valoración para la moneda local 2-Check: -Datatype:CURR-Len:(13,2)
		, [VALUT] VARCHAR(8)  NOT NULL  --  -Fecha valor-Check: -Datatype:DATS-Len:(8,0)
		, [ZUONR] VARCHAR(18)  NOT NULL  --  -Número de asignación-Check: -Datatype:CHAR-Len:(18,0)
		, [SGTXT] VARCHAR(50)  NOT NULL  --  -Texto posición-Check: -Datatype:CHAR-Len:(50,0)
		, [ZINKZ] VARCHAR(2)  NOT NULL  --  -Exclusión del cálculo de intereses-Check: -Datatype:CHAR-Len:(2,0)
		, [VBUND] VARCHAR(6)  NOT NULL  --  -Número de sociedad GL asociada-Check:T880-Datatype:CHAR-Len:(6,0)
		, [BEWAR] VARCHAR(3)  NOT NULL  --  -Cl.movimiento-Check:T856-Datatype:CHAR-Len:(3,0)
		, [ALTKT] VARCHAR(10)  NOT NULL  --  -Nº de cuenta de grupo-Check:*-Datatype:CHAR-Len:(10,0)
		, [VORGN] VARCHAR(4)  NOT NULL  --  -Clase de operación para General Ledger-Check: -Datatype:CHAR-Len:(4,0)
		, [FDLEV] VARCHAR(2)  NOT NULL  --  -Nivel gest.tesorería-Check:T036-Datatype:CHAR-Len:(2,0)
		, [FDGRP] VARCHAR(10)  NOT NULL  --  -Grupo de tesorería-Check:T035-Datatype:CHAR-Len:(10,0)
		, [FDWBT] DECIMAL(16,4)  NOT NULL  --  -Importe previsto en moneda de doc. o moneda de cta.mayor-Check: -Datatype:CURR-Len:(13,2)
		, [FDTAG] VARCHAR(8)  NOT NULL  --  -Fecha de tesorería-Check: -Datatype:DATS-Len:(8,0)
		, [FKONT] VARCHAR(3)  NOT NULL  --  -Posición del plan de tesorería-Check: -Datatype:NUMC-Len:(3,0)
		, [KOKRS] VARCHAR(4)  NOT NULL  --  -Sociedad CO-Check:TKA01-Datatype:CHAR-Len:(4,0)
		, [KOSTL] VARCHAR(10)  NOT NULL  --  -Centro de coste-Check:*-Datatype:CHAR-Len:(10,0)
		, [PROJN] VARCHAR(16)  NOT NULL  --  -Viejísimo : nº de proyecto: NO utilizar ->PS_POSNR-Check: -Datatype:CHAR-Len:(16,0)
		, [AUFNR] VARCHAR(12)  NOT NULL  --  -Número de orden-Check:AUFK-Datatype:CHAR-Len:(12,0)
		, [VBELN] VARCHAR(10)  NOT NULL  --  -Factura-Check:VBUK-Datatype:CHAR-Len:(10,0)
		, [VBEL2] VARCHAR(10)  NOT NULL  --  -Documento de ventas-Check:VBUK-Datatype:CHAR-Len:(10,0)
		, [POSN2] VARCHAR(6)  NOT NULL  --  -Posición documento ventas-Check:VBUP-Datatype:NUMC-Len:(6,0)
		, [ETEN2] VARCHAR(4)  NOT NULL  --  -Nº de reparto-Check:VBEP-Datatype:NUMC-Len:(4,0)
		, [ANLN1] VARCHAR(12)  NOT NULL  --  -Número principal de activo fijo-Check:ANLH-Datatype:CHAR-Len:(12,0)
		, [ANLN2] VARCHAR(4)  NOT NULL  --  -Subnúmero de activo fijo-Check:ANLA-Datatype:CHAR-Len:(4,0)
		, [ANBWA] VARCHAR(3)  NOT NULL  --  -Clase de movimiento de activos fijos-Check:TABW-Datatype:CHAR-Len:(3,0)
		, [BZDAT] VARCHAR(8)  NOT NULL  --  -Fecha de referencia-Check: -Datatype:DATS-Len:(8,0)
		, [PERNR] VARCHAR(8)  NOT NULL  --  -Número de personal-Check: -Datatype:NUMC-Len:(8,0)
		, [XUMSW] VARCHAR(1)  NOT NULL  --  -Indicador: ¿Posición con efecto sobre las ventas?-Check: -Datatype:CHAR-Len:(1,0)
		, [XHRES] VARCHAR(1)  NOT NULL  --  -Indicador: Cuenta de mayor residente-Check: -Datatype:CHAR-Len:(1,0)
		, [XKRES] VARCHAR(1)  NOT NULL  --  -Indicador: ¿PI pueden visualizarse mediante cuenta?-Check: -Datatype:CHAR-Len:(1,0)
		, [XOPVW] VARCHAR(1)  NOT NULL  --  -Indicador: ¿Gestión de partidas abiertas?-Check: -Datatype:CHAR-Len:(1,0)
		, [XCPDD] VARCHAR(1)  NOT NULL  --  -Ind.: Dirección y datos bancarios fijados individualmente-Check: -Datatype:CHAR-Len:(1,0)
		, [XSKST] VARCHAR(1)  NOT NULL  --  -Indicador: Contabilización estadística a centro de coste-Check: -Datatype:CHAR-Len:(1,0)
		, [XSAUF] VARCHAR(1)  NOT NULL  --  -Indicador: Contabilización a orden es estadística-Check: -Datatype:CHAR-Len:(1,0)
		, [XSPRO] VARCHAR(1)  NOT NULL  --  -Indicador: Contabilización a proyectos es estadística-Check: -Datatype:CHAR-Len:(1,0)
		, [XSERG] VARCHAR(1)  NOT NULL  --  -Indicador: la contabilización en el resultado es estadística-Check: -Datatype:CHAR-Len:(1,0)
		, [XFAKT] VARCHAR(1)  NOT NULL  --  -Indicador: ¿ Se actualizó la factura ?-Check: -Datatype:CHAR-Len:(1,0)
		, [XUMAN] VARCHAR(1)  NOT NULL  --  -Indicador: ¿ Traslado de anticipo ?-Check: -Datatype:CHAR-Len:(1,0)
		, [XANET] VARCHAR(1)  NOT NULL  --  -Indicador: ¿ Anticipo en procedimiento neto ?-Check: -Datatype:CHAR-Len:(1,0)
		, [XSKRL] VARCHAR(1)  NOT NULL  --  -Indicador: ¿Apunte sin relevancia para DPP?-Check: -Datatype:CHAR-Len:(1,0)
		, [XINVE] VARCHAR(1)  NOT NULL  --  -Indicador: ¿se trata de bienes de inversión?-Check: -Datatype:CHAR-Len:(1,0)
		, [XPANZ] VARCHAR(1)  NOT NULL  --  -Visualizar posición-Check: -Datatype:CHAR-Len:(1,0)
		, [XAUTO] VARCHAR(1)  NOT NULL  --  -Indicador: Posición creada automáticamente-Check: -Datatype:CHAR-Len:(1,0)
		, [XNCOP] VARCHAR(1)  NOT NULL  --  -Indicador: ¿ Partida no copiable ?-Check: -Datatype:CHAR-Len:(1,0)
		, [XZAHL] VARCHAR(1)  NOT NULL  --  -Indicador: ¿Se trata de una operación de pago?-Check: -Datatype:CHAR-Len:(1,0)
		, [SAKNR] VARCHAR(10)  NOT NULL  --  -Número de la cuenta de mayor-Check:SKB1-Datatype:CHAR-Len:(10,0)
		, [HKONT] VARCHAR(10)  NOT NULL  --  -Cuenta de mayor de la contabilidad principal-Check:SKB1-Datatype:CHAR-Len:(10,0)
		, [KUNNR] VARCHAR(10)  NOT NULL  --  -Número de deudor-Check:KNA1-Datatype:CHAR-Len:(10,0)
		, [LIFNR] VARCHAR(10)  NOT NULL  --  -Número de cuenta del proveedor o acreedor-Check:LFA1-Datatype:CHAR-Len:(10,0)
		, [FILKD] VARCHAR(10)  NOT NULL  --  -Número de cuenta de la subsidiaria-Check: -Datatype:CHAR-Len:(10,0)
		, [XBILK] VARCHAR(1)  NOT NULL  --  -Indicador: ¿Es la cuenta una cuenta de balance?-Check: -Datatype:CHAR-Len:(1,0)
		, [GVTYP] VARCHAR(2)  NOT NULL  --  -Tp.cta.beneficios-Check: -Datatype:CHAR-Len:(2,0)
		, [HZUON] VARCHAR(18)  NOT NULL  --  -Número de asignación para cuentas de mayor especiales-Check: -Datatype:CHAR-Len:(18,0)
		, [ZFBDT] VARCHAR(8)  NOT NULL  --  -Fecha base para cálculo del vencimiento-Check: -Datatype:DATS-Len:(8,0)
		, [ZTERM] VARCHAR(4)  NOT NULL  --  -Clave de condiciones de pago-Check: -Datatype:CHAR-Len:(4,0)
		, [ZBD1T] INT NOT NULL  --  -Días del descuento por pronto pago 1-Check: -Datatype:DEC-Len:(3,0)
		, [ZBD2T] INT NOT NULL  --  -Días del descuento por pronto pago 2-Check: -Datatype:DEC-Len:(3,0)
		, [ZBD3T] INT NOT NULL  --  -Plazo para condición de pago neto-Check: -Datatype:DEC-Len:(3,0)
		, [ZBD1P] DECIMAL(16,4)  NOT NULL  --  -Porcentaje de descuento por pronto pago 1-Check: -Datatype:DEC-Len:(5,3)
		, [ZBD2P] DECIMAL(16,4)  NOT NULL  --  -Porcentaje de descuento por pronto pago 2-Check: -Datatype:DEC-Len:(5,3)
		, [SKFBT] DECIMAL(16,4)  NOT NULL  --  -Importe con derecho a descuento en moneda del documento-Check: -Datatype:CURR-Len:(13,2)
		, [SKNTO] DECIMAL(16,4)  NOT NULL  --  -Importe del descuento en moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [WSKTO] DECIMAL(16,4)  NOT NULL  --  -Importe del descuento en moneda del documento-Check: -Datatype:CURR-Len:(13,2)
		, [ZLSCH] VARCHAR(1)  NOT NULL  --  -Vía de pago-Check:T042Z-Datatype:CHAR-Len:(1,0)
		, [ZLSPR] VARCHAR(1)  NOT NULL  --  -Clave para bloqueo de pago-Check:T008-Datatype:CHAR-Len:(1,0)
		, [ZBFIX] VARCHAR(1)  NOT NULL  --  -Condición de pago fija-Check: -Datatype:CHAR-Len:(1,0)
		, [HBKID] VARCHAR(5)  NOT NULL  --  -Clave breve para banco propio-Check:T012-Datatype:CHAR-Len:(5,0)
		, [BVTYP] VARCHAR(4)  NOT NULL  --  -Tipo de banco interlocutor-Check: -Datatype:CHAR-Len:(4,0)
		, [NEBTR] DECIMAL(16,4)  NOT NULL  --  -Importe neto del pago-Check: -Datatype:CURR-Len:(13,2)
		, [MWSK1] VARCHAR(2)  NOT NULL  --  -Indicador de impuestos para reparto-Check:T007A-Datatype:CHAR-Len:(2,0)
		, [DMBT1] DECIMAL(16,4)  NOT NULL  --  -Cuota en moneda local para reparto de impuestos-Check: -Datatype:CURR-Len:(13,2)
		, [WRBT1] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda extranjera para reparto del impuesto-Check: -Datatype:CURR-Len:(13,2)
		, [MWSK2] VARCHAR(2)  NOT NULL  --  -Indicador de impuestos para reparto-Check:T007A-Datatype:CHAR-Len:(2,0)
		, [DMBT2] DECIMAL(16,4)  NOT NULL  --  -Cuota en moneda local para reparto de impuestos-Check: -Datatype:CURR-Len:(13,2)
		, [WRBT2] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda extranjera para reparto del impuesto-Check: -Datatype:CURR-Len:(13,2)
		, [MWSK3] VARCHAR(2)  NOT NULL  --  -Indicador de impuestos para reparto-Check:T007A-Datatype:CHAR-Len:(2,0)
		, [DMBT3] DECIMAL(16,4)  NOT NULL  --  -Cuota en moneda local para reparto de impuestos-Check: -Datatype:CURR-Len:(13,2)
		, [WRBT3] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda extranjera para reparto del impuesto-Check: -Datatype:CURR-Len:(13,2)
		, [REBZG] VARCHAR(10)  NOT NULL  --  -Número documento de factura a la que pertenece la operación-Check: -Datatype:CHAR-Len:(10,0)
		, [REBZJ] VARCHAR(4)  NOT NULL  --  -Ejercicio de la factura correspondiente (para abonos)-Check: -Datatype:NUMC-Len:(4,0)
		, [REBZZ] VARCHAR(3)  NOT NULL  --  -Posición en la factura correspondiente-Check: -Datatype:NUMC-Len:(3,0)
		, [REBZT] VARCHAR(1)  NOT NULL  --  -Clase documento subsiguiente-Check: -Datatype:CHAR-Len:(1,0)
		, [ZOLLT] VARCHAR(8)  NOT NULL  --  -Número de la tasa arancelaria-Check: -Datatype:CHAR-Len:(8,0)
		, [ZOLLD] VARCHAR(8)  NOT NULL  --  -Fecha de aduana-Check: -Datatype:DATS-Len:(8,0)
		, [LZBKZ] VARCHAR(3)  NOT NULL  --  -Indicador del banco central regional-Check:T015L-Datatype:CHAR-Len:(3,0)
		, [LANDL] VARCHAR(3)  NOT NULL  --  -País proveedor-Check:T005-Datatype:CHAR-Len:(3,0)
		, [DIEKZ] VARCHAR(1)  NOT NULL  --  -Indicador de prestación de servicios (pagos al extranjero)-Check: -Datatype:CHAR-Len:(1,0)
		, [SAMNR] VARCHAR(8)  NOT NULL  --  -Número de la lista de facturas-Check: -Datatype:NUMC-Len:(8,0)
		, [ABPER] VARCHAR(6)  NOT NULL  --  -Período de liquidación-Check: -Datatype:ACCP-Len:(6,0)
		, [VRSKZ] VARCHAR(1)  NOT NULL  --  -Indicador de seguro-Check: -Datatype:CHAR-Len:(1,0)
		, [VRSDT] VARCHAR(8)  NOT NULL  --  -Fecha de seguro-Check: -Datatype:DATS-Len:(8,0)
		, [DISBN] VARCHAR(10)  NOT NULL  --  -Nº del documento de utilización de L/C (doc. de descuento)-Check: -Datatype:CHAR-Len:(10,0)
		, [DISBJ] VARCHAR(4)  NOT NULL  --  -Ejercicio del documento de utilización de L/C-Check: -Datatype:NUMC-Len:(4,0)
		, [DISBZ] VARCHAR(3)  NOT NULL  --  -Apunte dentro de un documento de utilización de L/C-Check: -Datatype:NUMC-Len:(3,0)
		, [WVERW] VARCHAR(1)  NOT NULL  --  -Clase utilización efecto-Check: -Datatype:CHAR-Len:(1,0)
		, [ANFBN] VARCHAR(10)  NOT NULL  --  -Número de documento de la solicitud de aceptación de L/C-Check: -Datatype:CHAR-Len:(10,0)
		, [ANFBJ] VARCHAR(4)  NOT NULL  --  -Ejercicio del documento de solicitud de aceptación de L/C-Check: -Datatype:NUMC-Len:(4,0)
		, [ANFBU] VARCHAR(4)  NOT NULL  --  -Sociedad en la que está contabilizada la sol.acept. L/C-Check:T001-Datatype:CHAR-Len:(4,0)
		, [ANFAE] VARCHAR(8)  NOT NULL  --  -Vencimiento de la solicitud de aceptación de L/C-Check: -Datatype:DATS-Len:(8,0)
		, [BLNBT] DECIMAL(16,4)  NOT NULL  --  -Importe base para cálculo del importe de preferencia-Check: -Datatype:CURR-Len:(13,2)
		, [BLNKZ] VARCHAR(2)  NOT NULL  --  -(obsoleto) Indicador subvención p.cálculo ptje.reducción-Check:*-Datatype:CHAR-Len:(2,0)
		, [BLNPZ] DECIMAL(16,4)  NOT NULL  --  -Porcentaje de preferencia-Check: -Datatype:DEC-Len:(7,2)
		, [MSCHL] VARCHAR(1)  NOT NULL  --  -Clave de reclamación-Check:T040-Datatype:CHAR-Len:(1,0)
		, [MANSP] VARCHAR(1)  NOT NULL  --  -Bloqueo de reclamación-Check:T040S-Datatype:CHAR-Len:(1,0)
		, [MADAT] VARCHAR(8)  NOT NULL  --  -Fecha de la última reclamación-Check: -Datatype:DATS-Len:(8,0)
		, [MANST] VARCHAR(1)  NOT NULL  --  -Nivel de reclamación-Check: -Datatype:NUMC-Len:(1,0)
		, [MABER] VARCHAR(2)  NOT NULL  --  -Área de reclamación-Check:T047M-Datatype:CHAR-Len:(2,0)
		, [ESRNR] VARCHAR(11)  NOT NULL  --  -Nº de usuario ESR-Check: -Datatype:CHAR-Len:(11,0)
		, [ESRRE] VARCHAR(27)  NOT NULL  --  -Nº referencia ESR-Check: -Datatype:CHAR-Len:(27,0)
		, [ESRPZ] VARCHAR(2)  NOT NULL  --  -Dígito de control ESR-Check: -Datatype:CHAR-Len:(2,0)
		, [KLIBT] DECIMAL(16,4)  NOT NULL  --  -Importe para el control de créditos-Check: -Datatype:CURR-Len:(13,2)
		, [QSZNR] VARCHAR(10)  NOT NULL  --  -Número del certificado de exención de la retención impuestos-Check: -Datatype:CHAR-Len:(10,0)
		, [QBSHB] DECIMAL(16,4)  NOT NULL  --  -Importe de retención (en moneda del documento)-Check: -Datatype:CURR-Len:(13,2)
		, [QSFBT] DECIMAL(16,4)  NOT NULL  --  -Importe exento de retención (en moneda del documento)-Check: -Datatype:CURR-Len:(13,2)
		, [NAVHW] DECIMAL(16,4)  NOT NULL  --  -IVA soportado no deducible (en moneda local)-Check: -Datatype:CURR-Len:(13,2)
		, [NAVFW] DECIMAL(16,4)  NOT NULL  --  -IVA soportado no deducible (en moneda del documento)-Check: -Datatype:CURR-Len:(13,2)
		, [MATNR] VARCHAR(18)  NOT NULL  --  -Número de material-Check:MARA-Datatype:CHAR-Len:(18,0)
		, [WERKS] VARCHAR(4)  NOT NULL  --  -Centro-Check:T001W-Datatype:CHAR-Len:(4,0)
		, [MENGE] DECIMAL(16,4)  NOT NULL  --  -Cantidad-Check: -Datatype:QUAN-Len:(13,3)
		, [MEINS] VARCHAR(3)  NOT NULL  --  -Unidad de medida base-Check:T006-Datatype:UNIT-Len:(3,0)
		, [ERFMG] DECIMAL(16,4)  NOT NULL  --  -Cantidad en unidad de medida de entrada-Check: -Datatype:QUAN-Len:(13,3)
		, [ERFME] VARCHAR(3)  NOT NULL  --  -Unidad de medida de entrada-Check:T006-Datatype:UNIT-Len:(3,0)
		, [BPMNG] DECIMAL(16,4)  NOT NULL  --  -Cantidad en unidad de medida de precio de pedido-Check: -Datatype:QUAN-Len:(13,3)
		, [BPRME] VARCHAR(3)  NOT NULL  --  -Unidad medida de precio de pedido-Check:T006-Datatype:UNIT-Len:(3,0)
		, [EBELN] VARCHAR(10)  NOT NULL  --  -Número del documento de compras-Check:EKKO-Datatype:CHAR-Len:(10,0)
		, [EBELP] VARCHAR(5)  NOT NULL  --  -Número de posición del documento de compras-Check:EKPO-Datatype:NUMC-Len:(5,0)
		, [ZEKKN] VARCHAR(2)  NOT NULL  --  -Número actual de la imputación-Check: -Datatype:NUMC-Len:(2,0)
		, [ELIKZ] VARCHAR(1)  NOT NULL  --  -Indicador de entrega final-Check: -Datatype:CHAR-Len:(1,0)
		, [VPRSV] VARCHAR(1)  NOT NULL  --  -Indicador de control de precios-Check: -Datatype:CHAR-Len:(1,0)
		, [PEINH] INT NOT NULL  --  -Cantidad base-Check: -Datatype:DEC-Len:(5,0)
		, [BWKEY] VARCHAR(4)  NOT NULL  --  -Ámbito de valoración-Check:T001K-Datatype:CHAR-Len:(4,0)
		, [BWTAR] VARCHAR(10)  NOT NULL  --  -Clase de valoración-Check:T149D-Datatype:CHAR-Len:(10,0)
		, [BUSTW] VARCHAR(4)  NOT NULL  --  -String de contabilización para valores-Check: -Datatype:CHAR-Len:(4,0)
		, [REWRT] DECIMAL(16,4)  NOT NULL  --  -Valor de factura registrado en moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [REWWR] DECIMAL(16,4)  NOT NULL  --  -Valor de factura entrado (en moneda extranjera)-Check: -Datatype:CURR-Len:(13,2)
		, [BONFB] DECIMAL(16,4)  NOT NULL  --  -Importe con derecho a rappel en moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [BUALT] DECIMAL(16,4)  NOT NULL  --  -Importe contab.en control alternativo de precios-Check: -Datatype:CURR-Len:(13,2)
		, [PSALT] VARCHAR(1)  NOT NULL  --  -Control alternativo de precios-Check: -Datatype:CHAR-Len:(1,0)
		, [NPREI] DECIMAL(16,4)  NOT NULL  --  -Precio nuevo-Check: -Datatype:CURR-Len:(11,2)
		, [TBTKZ] VARCHAR(1)  NOT NULL  --  -Indicador: Cargo posterior-Check: -Datatype:CHAR-Len:(1,0)
		, [SPGRP] VARCHAR(1)  NOT NULL  --  -Motivo de bloqueo precio-Check: -Datatype:CHAR-Len:(1,0)
		, [SPGRM] VARCHAR(1)  NOT NULL  --  -Motivo del bloqueo cantidad-Check: -Datatype:CHAR-Len:(1,0)
		, [SPGRT] VARCHAR(1)  NOT NULL  --  -Motivo-bloqueo Plazo-Check: -Datatype:CHAR-Len:(1,0)
		, [SPGRG] VARCHAR(1)  NOT NULL  --  -Motivo de bloqueo: Cantidad de precio de pedido-Check: -Datatype:CHAR-Len:(1,0)
		, [SPGRV] VARCHAR(1)  NOT NULL  --  -Motivo bloqueo presupuesto proyecto-Check: -Datatype:CHAR-Len:(1,0)
		, [SPGRQ] VARCHAR(1)  NOT NULL  --  -Motivo bloqueo manual-Check: -Datatype:CHAR-Len:(1,0)
		, [STCEG] VARCHAR(20)  NOT NULL  --  -Número de identificación fiscal comunitario-Check: -Datatype:CHAR-Len:(20,0)
		, [EGBLD] VARCHAR(3)  NOT NULL  --  -País de destino para la entrega de mercancías-Check:T005-Datatype:CHAR-Len:(3,0)
		, [EGLLD] VARCHAR(3)  NOT NULL  --  -País de entrega en la entrega de mercancías-Check:T005-Datatype:CHAR-Len:(3,0)
		, [RSTGR] VARCHAR(3)  NOT NULL  --  -Origen de las diferencias en los pagos-Check:T053R-Datatype:CHAR-Len:(3,0)
		, [RYACQ] VARCHAR(4)  NOT NULL  --  -Año de alta-Check: -Datatype:CHAR-Len:(4,0)
		, [RPACQ] VARCHAR(3)  NOT NULL  --  -Período de alta-Check: -Datatype:NUMC-Len:(3,0)
		, [RDIFF] DECIMAL(16,4)  NOT NULL  --  -Beneficio/Pérdida por tipo de cambio realizado-Check: -Datatype:CURR-Len:(13,2)
		, [RDIF2] DECIMAL(16,4)  NOT NULL  --  -Diferencia de T/C realizada para la segunda moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [PRCTR] VARCHAR(10)  NOT NULL  --  -Centro de beneficio-Check:*-Datatype:CHAR-Len:(10,0)
		, [XHKOM] VARCHAR(1)  NOT NULL  --  -Indicador: Imputación manual a cuenta de mayor-Check: -Datatype:CHAR-Len:(1,0)
		, [VNAME] VARCHAR(6)  NOT NULL  --  -Joint Venture-Check:T8JV-Datatype:CHAR-Len:(6,0)
		, [RECID] VARCHAR(2)  NOT NULL  --  -Tipo de coste-Check:T8JJ-Datatype:CHAR-Len:(2,0)
		, [EGRUP] VARCHAR(3)  NOT NULL  --  -Grupo de participación-Check:T8JF-Datatype:CHAR-Len:(3,0)
		, [VPTNR] VARCHAR(10)  NOT NULL  --  -Nº de cliente del interlocutor-Check:KNA1-Datatype:CHAR-Len:(10,0)
		, [VERTT] VARCHAR(1)  NOT NULL  --  -Clase de contrato-Check: -Datatype:CHAR-Len:(1,0)
		, [VERTN] VARCHAR(13)  NOT NULL  --  -Número de contrato-Check: -Datatype:CHAR-Len:(13,0)
		, [VBEWA] VARCHAR(4)  NOT NULL  --  -Clase de movimiento-Check:*-Datatype:CHAR-Len:(4,0)
		, [DEPOT] VARCHAR(10)  NOT NULL  --  -Depósito-Check:*-Datatype:CHAR-Len:(10,0)
		, [TXJCD] VARCHAR(15)  NOT NULL  --  -Domicilio fiscal-Check:TTXJ-Datatype:CHAR-Len:(15,0)
		, [IMKEY] VARCHAR(8)  NOT NULL  --  -Clave interna para objeto inmueble-Check: -Datatype:CHAR-Len:(8,0)
		, [DABRZ] VARCHAR(8)  NOT NULL  --  -Fecha de referencia para la liquidación-Check: -Datatype:DATS-Len:(8,0)
		, [POPTS] DECIMAL(16,4)  NOT NULL  --  -Tasa de opción para bienes inmuebles-Check: -Datatype:DEC-Len:(9,6)
		, [FIPOS] VARCHAR(14)  NOT NULL  --  -Posición presupuestaria-Check:*-Datatype:CHAR-Len:(14,0)
		, [KSTRG] VARCHAR(12)  NOT NULL  --  -Objeto de coste-Check:*-Datatype:CHAR-Len:(12,0)
		, [NPLNR] VARCHAR(12)  NOT NULL  --  -Número de grafo para imputación-Check:*-Datatype:CHAR-Len:(12,0)
		, [AUFPL] VARCHAR(10)  NOT NULL  --  -Número de hoja de ruta para operaciones en la orden-Check: -Datatype:NUMC-Len:(10,0)
		, [APLZL] VARCHAR(8)  NOT NULL  --  -Contador general de la orden-Check:*-Datatype:NUMC-Len:(8,0)
		, [PROJK] VARCHAR(8)  NOT NULL  --  -Elemento del plan de estructura de proyecto (elemento PEP)-Check:*-Datatype:NUMC-Len:(8,0)
		, [PAOBJNR] VARCHAR(10)  NOT NULL  --  -Número para objetos PA (CO-PA)-Check: -Datatype:NUMC-Len:(10,0)
		, [PASUBNR] VARCHAR(4)  NOT NULL  --  -Historial de modificación para objetos PA (CO-PA)-Check: -Datatype:NUMC-Len:(4,0)
		, [SPGRS] VARCHAR(1)  NOT NULL  --  -Motivo del bloqueo: Magnitud del importe-Check: -Datatype:CHAR-Len:(1,0)
		, [SPGRC] VARCHAR(1)  NOT NULL  --  -Motivo del bloqueo calidad-Check: -Datatype:CHAR-Len:(1,0)
		, [BTYPE] VARCHAR(2)  NOT NULL  --  -Tipo de liquidación-Check:T8JA-Datatype:CHAR-Len:(2,0)
		, [ETYPE] VARCHAR(3)  NOT NULL  --  -Clase de participación-Check:T8JE-Datatype:CHAR-Len:(3,0)
		, [XEGDR] VARCHAR(1)  NOT NULL  --  -Indicador: ¿operación triangular dentro de la UE?-Check: -Datatype:CHAR-Len:(1,0)
		, [LNRAN] VARCHAR(5)  NOT NULL  --  -Nº actual de partida individual de activo fijo en ejercicio-Check:*-Datatype:NUMC-Len:(5,0)
		, [HRKFT] VARCHAR(4)  NOT NULL  --  -Grupo de orígenes como subdivisión de la clase de coste-Check:*-Datatype:CHAR-Len:(4,0)
		, [DMBE2] DECIMAL(16,4)  NOT NULL  --  -Importe en la segunda moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [DMBE3] DECIMAL(16,4)  NOT NULL  --  -Importe en la tercera moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [DMB21] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda local 2 para reparto de impuestos-Check: -Datatype:CURR-Len:(13,2)
		, [DMB22] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda local 2 para reparto de impuestos-Check: -Datatype:CURR-Len:(13,2)
		, [DMB23] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda local 2 para reparto de impuestos-Check: -Datatype:CURR-Len:(13,2)
		, [DMB31] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda local 3 para reparto de impuestos-Check: -Datatype:CURR-Len:(13,2)
		, [DMB32] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda local 3 para reparto de impuestos-Check: -Datatype:CURR-Len:(13,2)
		, [DMB33] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda local 3 para reparto de impuestos-Check: -Datatype:CURR-Len:(13,2)
		, [MWST2] DECIMAL(16,4)  NOT NULL  --  -Cuota de IVA en moneda local 2-Check: -Datatype:CURR-Len:(13,2)
		, [MWST3] DECIMAL(16,4)  NOT NULL  --  -Cuota de IVA en moneda local 3-Check: -Datatype:CURR-Len:(13,2)
		, [NAVH2] DECIMAL(16,4)  NOT NULL  --  -IVA soportado no deducible en moneda local 2-Check: -Datatype:CURR-Len:(13,2)
		, [NAVH3] DECIMAL(16,4)  NOT NULL  --  -IVA soportado no deducible en moneda local 3-Check: -Datatype:CURR-Len:(13,2)
		, [SKNT2] DECIMAL(16,4)  NOT NULL  --  -Importe de descuento en moneda local 2-Check: -Datatype:CURR-Len:(13,2)
		, [SKNT3] DECIMAL(16,4)  NOT NULL  --  -Importe de descuento en moneda local 3-Check: -Datatype:CURR-Len:(13,2)
		, [BDIF3] DECIMAL(16,4)  NOT NULL  --  -Diferencia de valoración para la tercera moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [RDIF3] DECIMAL(16,4)  NOT NULL  --  -Diferencia de T/C realizada para la tercera moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [HWMET] VARCHAR(1)  NOT NULL  --  -Método con el cual se determinó el importe en mon.local-Check: -Datatype:CHAR-Len:(1,0)
		, [GLUPM] VARCHAR(1)  NOT NULL  --  -Método de actualización para integración CP - FI-CA-Check: -Datatype:CHAR-Len:(1,0)
		, [XRAGL] VARCHAR(1)  NOT NULL  --  -Indicador: La compensación ha sido anulada-Check: -Datatype:CHAR-Len:(1,0)
		, [UZAWE] VARCHAR(2)  NOT NULL  --  -Suplemento para la vía de pago-Check:T042F-Datatype:CHAR-Len:(2,0)
		, [LOKKT] VARCHAR(10)  NOT NULL  --  -Nº de cuenta alternativo en la sociedad-Check:*-Datatype:CHAR-Len:(10,0)
		, [FISTL] VARCHAR(16)  NOT NULL  --  -Centro gestor-Check:*-Datatype:CHAR-Len:(16,0)
		, [GEBER] VARCHAR(10)  NOT NULL  --  -Fondo-Check:*-Datatype:CHAR-Len:(10,0)
		, [STBUK] VARCHAR(4)  NOT NULL  --  -Sociedad impuestos-Check:*-Datatype:CHAR-Len:(4,0)
		, [TXBH2] DECIMAL(16,4)  NOT NULL  --  -Base imponible/Base imponible original en ML 2-Check: -Datatype:CURR-Len:(13,2)
		, [TXBH3] DECIMAL(16,4)  NOT NULL  --  -Base imponible/Base imponible original en ML 3-Check: -Datatype:CURR-Len:(13,2)
		, [PPRCT] VARCHAR(10)  NOT NULL  --  -Centro de beneficio interlocutor-Check:CEPC-Datatype:CHAR-Len:(10,0)
		, [XREF1] VARCHAR(12)  NOT NULL  --  -Clave de referencia de interlocutor comercial-Check: -Datatype:CHAR-Len:(12,0)
		, [XREF2] VARCHAR(12)  NOT NULL  --  -Clave de referencia de interlocutor comercial-Check: -Datatype:CHAR-Len:(12,0)
		, [KBLNR] VARCHAR(10)  NOT NULL  --  -Número de documento presupuestario-Check:KBLK-Datatype:CHAR-Len:(10,0)
		, [KBLPOS] VARCHAR(3)  NOT NULL  --  -Posición de documento: Documento presupuestario-Check:KBLP-Datatype:NUMC-Len:(3,0)
		, [STTAX] DECIMAL(16,4)  NOT NULL  --  -Importe de IVA como info estadística en moneda de documento-Check: -Datatype:CURR-Len:(13,2)
		, [FKBER] VARCHAR(4)  NOT NULL  --  -Área funcional-Check: -Datatype:CHAR-Len:(4,0)
		, [OBZEI] VARCHAR(3)  NOT NULL  --  -Número de la posición de documento en el documento original-Check: -Datatype:NUMC-Len:(3,0)
		, [XNEGP] VARCHAR(1)  NOT NULL  --  -Indicador: Contabilización negativa-Check: -Datatype:CHAR-Len:(1,0)
		, [RFZEI] VARCHAR(3)  NOT NULL  --  -Posición de tarjetas de pago-Check: -Datatype:NUMC-Len:(3,0)
		, [CCBTC] VARCHAR(10)  NOT NULL  --  -Tarjetas de pago: proceso de liquidación-Check: -Datatype:CHAR-Len:(10,0)
		, [KKBER] VARCHAR(4)  NOT NULL  --  -Área de control de créditos-Check:T014-Datatype:CHAR-Len:(4,0)
		, [EMPFB] VARCHAR(10)  NOT NULL  --  -Receptor del pago/Pagador-Check: -Datatype:CHAR-Len:(10,0)
		, [XREF3] VARCHAR(20)  NOT NULL  --  -Clave de referencia para la posición de documento-Check: -Datatype:CHAR-Len:(20,0)
		, [DTWS1] VARCHAR(2)  NOT NULL  --  -Instrucción 1-Check:*-Datatype:NUMC-Len:(2,0)
		, [DTWS2] VARCHAR(2)  NOT NULL  --  -Instrucción 2-Check:*-Datatype:NUMC-Len:(2,0)
		, [DTWS3] VARCHAR(2)  NOT NULL  --  -Instrucción 3-Check:*-Datatype:NUMC-Len:(2,0)
		, [DTWS4] VARCHAR(2)  NOT NULL  --  -Instrucción 4-Check:*-Datatype:NUMC-Len:(2,0)
		, [GRICD] VARCHAR(2)  NOT NULL  --  -Indicador de actividad p.el impuesto sobre ingresos brutos-Check:J_1AGICD-Datatype:CHAR-Len:(2,0)
		, [GRIRG] VARCHAR(3)  NOT NULL  --  -Región (Estado federal, ""land"", provincia, condado)-Check:T005S-Datatype:CHAR-Len:(3,0)
		, [GITYP] VARCHAR(2)  NOT NULL  --  -Clase de distribución para el I.R.P.F.-Check:J_1ADTYP-Datatype:CHAR-Len:(2,0)
		, [XPYPR] VARCHAR(1)  NOT NULL  --  -Indicador: para esta posición existe una orden de pago-Check: -Datatype:CHAR-Len:(1,0)
		, [KIDNO] VARCHAR(30)  NOT NULL  --  -Referencia de pago-Check: -Datatype:CHAR-Len:(30,0)
		, [ABSBT] DECIMAL(16,4)  NOT NULL  --  -Gestión de créditos: importe asegurado-Check: -Datatype:CURR-Len:(13,2)
		, [IDXSP] VARCHAR(5)  NOT NULL  --  -Índice de inflación-Check:J_1AINFT20-Datatype:CHAR-Len:(5,0)
		, [LINFV] VARCHAR(8)  NOT NULL  --  -Última fecha de ajuste-Check: -Datatype:DATS-Len:(8,0)
		, [KONTT] VARCHAR(2)  NOT NULL  --  -Tipo de imputación para solución sectorial-Check: -Datatype:CHAR-Len:(2,0)
		, [KONTL] VARCHAR(50)  NOT NULL  --  -Barra de imputación para imputaciones específicas de ramos-Check: -Datatype:CHAR-Len:(50,0)
		, [TXDAT] VARCHAR(8)  NOT NULL  --  -Fecha para determinar tipos impositivos-Check: -Datatype:DATS-Len:(8,0)
		, [AGZEI] INT NOT NULL  --  -Posición de compensación-Check: -Datatype:DEC-Len:(5,0)
		, [PYCUR] VARCHAR(5)  NOT NULL  --  -Importe para el pago automático-Check:TCURC-Datatype:CUKY-Len:(5,0)
		, [PYAMT] DECIMAL(16,4)  NOT NULL  --  -Importe en moneda de pago-Check: -Datatype:CURR-Len:(13,2)
		, [BUPLA] VARCHAR(4)  NOT NULL  --  -Lugar comercial-Check:J_1BBRANCH-Datatype:CHAR-Len:(4,0)
		, [SECCO] VARCHAR(4)  NOT NULL  --  -Sección de retención de impuestos-Check:SECCODE-Datatype:CHAR-Len:(4,0)
		, [LSTAR] VARCHAR(6)  NOT NULL  --  -Clase de actividad-Check:*-Datatype:CHAR-Len:(6,0)
		, [CESSION_KZ] VARCHAR(2)  NOT NULL  --  -Indicador cesión créditos-Check:TCESSION-Datatype:CHAR-Len:(2,0)
		, [PRZNR] VARCHAR(12)  NOT NULL  --  -Proceso empresarial-Check:*-Datatype:CHAR-Len:(12,0)
		, [PPDIFF] DECIMAL(16,4)  NOT NULL  --  -Beneficio/Pérdida por T/C realizado 1º ML (pago parcial)-Check: -Datatype:CURR-Len:(13,2)
		, [PPDIF2] DECIMAL(16,4)  NOT NULL  --  -Beneficio/Pérdida por T/C realizado 2º ML (pago parcial)-Check: -Datatype:CURR-Len:(13,2)
		, [PPDIF3] DECIMAL(16,4)  NOT NULL  --  -Beneficio/Pérdida por T/C realizado 3º ML (pago parcial)-Check: -Datatype:CURR-Len:(13,2)
		, [PENLC1] DECIMAL(16,4)  NOT NULL  --  -Penalty Charge Amount in First Local Currency-Check: -Datatype:CURR-Len:(13,2)
		, [PENLC2] DECIMAL(16,4)  NOT NULL  --  -Penalty Charge Amount in Second Local Currency-Check: -Datatype:CURR-Len:(13,2)
		, [PENLC3] DECIMAL(16,4)  NOT NULL  --  -Penalty Charge Amount in Third Local Currency-Check: -Datatype:CURR-Len:(13,2)
		, [PENFC] DECIMAL(16,4)  NOT NULL  --  -Penalty Charge Amount in Document Currency-Check: -Datatype:CURR-Len:(13,2)
		, [PENDAYS] INT NOT NULL  --  -Number of Days for Penalty Charge Calculation-Check: -Datatype:INT4-Len:(10,0)
		, [PENRC] VARCHAR(2)  NOT NULL  --  -Reason for Late Payment-Check: -Datatype:CHAR-Len:(2,0)
		, [GRANT_NBR] VARCHAR(20)  NOT NULL  --  -Subvención-Check:*-Datatype:CHAR-Len:(20,0)
		, [SCTAX] DECIMAL(16,4)  NOT NULL  --  -Participación impositiva FI-CA moneda local-Check: -Datatype:CURR-Len:(13,2)
		, [FKBER_LONG] VARCHAR(16)  NOT NULL  --  -Custodio del Activo-Check:*-Datatype:CHAR-Len:(16,0)
		, [GMVKZ] VARCHAR(1)  NOT NULL  --  -Partidas en ejecución-Check: -Datatype:CHAR-Len:(1,0)
		, [SRTYPE] VARCHAR(2)  NOT NULL  --  -Cl.crédito adicional-Check: -Datatype:CHAR-Len:(2,0)
		, [INTRENO] VARCHAR(13)  NOT NULL  --  -Codificación interna datos maestros bienes inmuebles-Check: -Datatype:CHAR-Len:(13,0)
		, [MEASURE] VARCHAR(24)  NOT NULL  --  -Programa de financiación-Check:*-Datatype:CHAR-Len:(24,0)
		, [AUGGJ] VARCHAR(4)  NOT NULL  --  -Ejercicio de doc.compensación-Check: -Datatype:NUMC-Len:(4,0)
		, [PPA_EX_IND] VARCHAR(1)  NOT NULL  --  -PPA Exclude Indicator-Check: -Datatype:CHAR-Len:(1,0)
		, [DOCLN] VARCHAR(6)  NOT NULL  --  -Posición de documento de seís posiciones para ledger-Check: -Datatype:CHAR-Len:(6,0)
		, [SEGMENT] VARCHAR(10)  NOT NULL  --  -Segmento para reporting de segmento-Check:*-Datatype:CHAR-Len:(10,0)
		, [PSEGMENT] VARCHAR(10)  NOT NULL  --  -Segmento de interlocutor para reporting de segmento-Check:*-Datatype:CHAR-Len:(10,0)
		, [PFKBER] VARCHAR(16)  NOT NULL  --  -Área de funciones del interlocutor-Check:*-Datatype:CHAR-Len:(16,0)
		, [HKTID] VARCHAR(5)  NOT NULL  --  -Clave breve para un banco/cuenta-Check:T012K-Datatype:CHAR-Len:(5,0)
		, [KSTAR] VARCHAR(10)  NOT NULL  --  -Clase de coste-Check:*-Datatype:CHAR-Len:(10,0)
		, [XLGCLR] VARCHAR(1)  NOT NULL  --  -Clearing Specific to Ledger Groups-Check: -Datatype:CHAR-Len:(1,0)
		, [PGEBER] VARCHAR(10)  NOT NULL  --  -Fond.interl.-Check:*-Datatype:CHAR-Len:(10,0)
		, [PGRANT_NBR] VARCHAR(20)  NOT NULL  --  -Subvención de interlocutor-Check:*-Datatype:CHAR-Len:(20,0)
		, [BUDGET_PD] VARCHAR(10)  NOT NULL  --  -CP: Período de presupuesto-Check:*-Datatype:CHAR-Len:(10,0)
		, [PBUDGET_PD] VARCHAR(10)  NOT NULL  --  -CP: Interlocutor període de presupuesto-Check:*-Datatype:CHAR-Len:(10,0)
		, [PEROP_BEG] VARCHAR(8)  NOT NULL  --  -Billing Period of Performance Start Date-Check: -Datatype:DATS-Len:(8,0)
		, [PEROP_END] VARCHAR(8)  NOT NULL  --  -Billing Period of Performance End Date-Check: -Datatype:DATS-Len:(8,0)
		, [FASTPAY] VARCHAR(1)  NOT NULL  --  -PPA Fast Pay Indicator-Check: -Datatype:CHAR-Len:(1,0)
		, [PRODPER] VARCHAR(8)  NOT NULL  --  -Mes de producción (para determinación de período y año)-Check: -Datatype:DATS-Len:(8,0)

	) ON [ps_DL_SAP_BSEG_AnioMes](AnioMes_Id)

	CREATE CLUSTERED COLUMNSTORE INDEX CS_DL_SAP_BSEG ON DL_SAP_BSEG ON [ps_DL_SAP_BSEG_AnioMes](AnioMes_Id)


	CREATE UNIQUE NONCLUSTERED INDEX PK_DL_SAP_BSEG ON DL_SAP_BSEG 
	(
		[BUKRS] ASC
		, [BELNR] ASC
		, [GJAHR] ASC
		, [BUZEI] ASC
		, [AnioMes_Id] ASC
	)
	ON [ps_DL_SAP_BSEG_AnioMes](AnioMes_Id)

	--DROP INDEX IX_DL_SAP_BSEG_DescId ON DL_SAP_BSEG
	CREATE NONCLUSTERED INDEX IX_DL_SAP_BSEG_Fecha ON DL_SAP_BSEG
	(
		[AEDAT] ASC
	) 
	ON [ps_DL_SAP_BSEG_AnioMes](AnioMes_Id) 
	

	DECLARE @FechaInicio AS DATE = '2019-01-01'
		, @FechaFin AS DATE = GETDATE()

	WHILE @FechaInicio <= @FechaFin
	BEGIN

		INSERT INTO DL_SAP_BSEG
		SELECT * FROM DWHDEV.DL_FARINTER.dbo.DL_SAP_BSEG WHERE AnioMes_Id >= YEAR(@FechaInicio) * 100 + MONTH(@FechaInicio)

		SET @FechaInicio = DATEADD(MONTH, 1, @FechaInicio)
	END
END