---
services:
  # Ejemplo de uso con devcontainer, esto hara que solo funcione en local/o remoto
  # dependiendo del montaje o no del espacio de trabajo respectivamente.
  dev:
    container_name: main-dagster-dev
    env_file: [./devcontainer.env]
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
      target: base  # El alias en Dockerfile
      # args: ["--sysctl", "net.ipv6.conf.all.disable_ipv6=1"]
    working_dir: /workspaces/main-dagster
    volumes:
      - main-dagster-devcontainer-ssh:/home/vscode/.ssh
      - shared-uv-cache:/home/vscode/.cache/uv
    #  - main-dagster-devcontainer-venv:/workspaces/main-dagster/.venv
    # Required for ptrace-based debuggers like C++, Go, and Rust
    # privileged: true
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
    # depends_on:
    #   - redis
    #   - mysql
    #   - toxiproxy
    ports: [3000:3000]
    command: [/bin/bash, -c, "sleep infinity\n"]
volumes:
  # Definición de volúmenes externos para mantener datos entre reinicios
  # Esto tambien acelera drasticamente la reconstruccion del contenedor
  main-dagster-devcontainer-ssh:
    external: true
  shared-uv-cache:
    external: true
  main-dagster-devcontainer-venv:
    external: true
