FROM mcr.microsoft.com/devcontainers/python:1-3.10-bookworm

RUN rm -f /etc/apt/sources.list.d/yarn.list \
    /etc/apt/sources.list.d/yarn.sources \
    /usr/share/keyrings/yarnkey.gpg \
    /etc/apt/keyrings/yarn-archive-keyring.gpg