--DROP TABLE IF EXISTS [DL_SAP_BSEG]
USE [DL_FARINTER]
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @sql AS NVARCHAR(4000)
--Puede recibir parametros desde python
DECLARE  @p_FechaDesde AS DATE = CASE WHEN TRY_CAST('{p_FechaDesde}' AS DATE) IS NOT NULL THEN '{p_FechaDesde}' ELSE NULL END
    , @p_IndicadorActualizarTodo bit = CASE WHEN TRY_CAST('{p_IndicadorActualizarTodo}' AS BIT) IS NOT NULL THEN '{p_IndicadorActualizarTodo}' ELSE NULL END
    ;

DECLARE
    @fechaInicio		AS DATE = GETDATE() - 30 --POR DEFECTO, evaluacion real más abajo
DECLARE @fechaInicioSAP AS NVARCHAR(10) = CONVERT(NVARCHAR(10), @fechaInicio, 112)
    , @AnioMesDesde AS INT = YEAR(@fechaInicio) * 100 + MONTH(@fechaInicio)
    , @AnioDesdeSAP AS NVARCHAR(4) = CAST(YEAR(@fechaInicio) AS NVARCHAR(4))
    , @TiempoInicio AS DATETIME = GETDATE()
    , @Duracion_Minutos AS DECIMAL(16, 4)
    , @Filas AS INT = 0

BEGIN try
    --###Mantenimiento Particiones
    IF (DATEPART(HOUR, GETDATE()) >= 18 OR DATEPART(HOUR, GETDATE()) < 8)
    BEGIN	--DECLARE @FechaDesde AS DATE = DATEADD(MONTH, -1, GETDATE())
        EXEC [dbo].sp_UtilAgregarParticionSiguienteAnioMes @p_NombreTabla = 'DL_SAP_BSEG', @p_PeriodoTipo = 'Mensual' -- 'Mensual' or 'Anual' ;
            , @p_FechaBase = @fechaInicio, @p_BaseDatos = 'DL_FARINTER'
        EXEC sp_UtilComprimirColumnstoresSiAplica @p_Tabla = 'DL_SAP_BSEG', @p_Fecha = @fechaInicio, @p_Tipo = 'YYYYMM', @p_BaseDatos = 'DL_FARINTER' --, @p_IndicadorForzado = 1
            --, @p_MantenimientoRealizado = @MantenimientoColumnstore OUTPUT;
        EXEC dbo.sp_UtilComprimirIndicesParticionesAnteriores @p_Tabla = 'DL_SAP_BSEG', @p_Fecha = @fechaInicio, @p_Tipo = 'YYYYMM', @p_BaseDatos = 'DL_FARINTER';
    END

    --###Revisar que estamos en DEV con el nombre de la instancia ojo!!!! no se puede ejecutar esto sin una asignacion a una variable primero.
    DECLARE @ServidorActual AS NVARCHAR(255) = CONVERT(NVARCHAR(255), SERVERPROPERTY('servername'))
    IF @ServidorActual NOT LIKE '%DEV%' OR @ServidorActual IS NULL
    BEGIN
        PRINT CONCAT('No se puede ejecutar en ', @ServidorActual	, ', solo se puede ejecutar en DEV')
        RETURN
    END
    --PRINT CONCAT('Ejecutando en ', @ServidorActual)

    -- select top 100 * FROM DL_FARINTER.dbo.DL_SAP_BSEG ORDER BY TDFDATE DESC

    -- exec DL_FARINTER.[dbo].[DL_paCargarSAP_Replica_BSEG]
    SET @sql = CONCAT('DL_paCargarSAP_Replica_BSEG', '')
    EXEC DL_FARINTER.[dbo].DL_paEscBitacora
        @Mensaje = @sql, @Tipo = 'Iniciado', @Tabla = 'DL_SAP_BSEG' 

    IF NOT EXISTS (SELECT TOP 1 1 FROM DL_FARINTER.dbo.DL_SAP_BSEG)
        SET @p_IndicadorActualizarTodo = 1
    
    IF @p_FechaDesde IS NULL
        set @AnioMesDesde = (SELECT MAX(AnioMes_Id) FROM DL_FARINTER.dbo.DL_SAP_BSEG WITH(NOLOCK))
    ELSE
        set @AnioMesDesde = YEAR(@p_FechaDesde) * 100 + MONTH(@p_FechaDesde)
    SET @fechaInicio =  COALESCE(@p_FechaDesde
        , DATEADD(DAY, -1, (
            --DECLARE @AnioMesDesde INT = (SELECT MAX(AnioMes_Id) FROM DL_FARINTER.dbo.DL_SAP_BSEG)
            SELECT CONVERT(DATE,MAX([AEDAT]),112) 
            FROM [DL_FARINTER].[dbo].[DL_SAP_BSEG] P
            WHERE P.AnioMes_Id = @AnioMesDesde
            ))
        , @fechaInicio)
    --Si existe una fecha mayor al dia de hoy, se toma la fecha de hoy menos 1
    IF @fechaInicio > GETDATE()-1 SET @fechaInicio = GETDATE()-1
    --Dos años atras máximo si se especifica actualizar todo
    IF @p_IndicadorActualizarTodo = 1 SET @fechaInicio = DATEFROMPARTS(year(GETDATE())-1, 1, 1)
    SET @fechaInicioSAP = CONVERT(NVARCHAR(10), @fechaInicio, 112);
    SET @AnioMesDesde = YEAR(@fechaInicio) * 100 + MONTH(@fechaInicio);
    SET @AnioDesdeSAP = LEFT(@fechaInicioSAP, 4);
    PRINT CONCAT('Cargando desde ', @fechaInicioSAP, ' Fecha: ', CONVERT(NVARCHAR(10), @fechaInicio, 112), ' AnioMes: ', @AnioMesDesde);
    
    BEGIN TRANSACTION
    IF @p_IndicadorActualizarTodo = 1
        TRUNCATE TABLE DL_FARINTER.dbo.DL_SAP_BSEG;

    --DECLARE @fechaInicioSAP VARCHAR(10) = '20240615'
    DROP TABLE IF EXISTS #DL_SAP_BSEG_TEMP4578621
    SELECT * INTO #DL_SAP_BSEG_TEMP4578621 
    FROM (SELECT * FROM DWHPRD.DL_FARINTER.dbo.DL_SAP_BSEG WHERE 1=0) T
    ;
    --CREATE CLUSTERED COLUMNSTORE INDEX CS_DL_SAP_BSEG_TEMP4578621 ON #DL_SAP_BSEG_TEMP4578621 ;

    DECLARE @Query VARCHAR(MAX) = 
        CONCAT('SELECT * '
        ,'FROM DL_FARINTER.dbo.DL_SAP_BSEG P '
        ,'WHERE P.AEDAT >= ''' , @fechaInicioSAP, ''''
        ,'AND P.AnioMes_Id >= ', @AnioMesDesde-000500) --5 Años atras cualquier cambio
        --SELECT @Query
    INSERT INTO #DL_SAP_BSEG_TEMP4578621 EXEC(@Query) AT DWHPRD

    MERGE INTO [dbo].[DL_SAP_BSEG] AS TARGET 
    USING (SELECT * FROM #DL_SAP_BSEG_TEMP4578621
        ) AS SOURCE
    ON TARGET.[AnioMes_Id] = SOURCE.[AnioMes_Id]
    AND TARGET.[BUKRS] = SOURCE.[BUKRS]
    AND TARGET.[BELNR] = SOURCE.[BELNR]
    AND TARGET.[GJAHR] = SOURCE.[GJAHR]
    AND TARGET.[BUZEI] = SOURCE.[BUZEI]
    WHEN MATCHED THEN
        UPDATE SET TARGET.[AEDAT] = SOURCE.[AEDAT]
            , TARGET.[BUZID] = SOURCE.[BUZID]
            , TARGET.[AUGDT] = SOURCE.[AUGDT]
            , TARGET.[AUGCP] = SOURCE.[AUGCP]
            , TARGET.[AUGBL] = SOURCE.[AUGBL]
            , TARGET.[BSCHL] = SOURCE.[BSCHL]
            , TARGET.[KOART] = SOURCE.[KOART]
            , TARGET.[UMSKZ] = SOURCE.[UMSKZ]
            , TARGET.[UMSKS] = SOURCE.[UMSKS]
            , TARGET.[ZUMSK] = SOURCE.[ZUMSK]
            , TARGET.[SHKZG] = SOURCE.[SHKZG]
            , TARGET.[GSBER] = SOURCE.[GSBER]
            , TARGET.[PARGB] = SOURCE.[PARGB]
            , TARGET.[MWSKZ] = SOURCE.[MWSKZ]
            , TARGET.[QSSKZ] = SOURCE.[QSSKZ]
            , TARGET.[DMBTR] = SOURCE.[DMBTR]
            , TARGET.[WRBTR] = SOURCE.[WRBTR]
            , TARGET.[KZBTR] = SOURCE.[KZBTR]
            , TARGET.[PSWBT] = SOURCE.[PSWBT]
            , TARGET.[PSWSL] = SOURCE.[PSWSL]
            , TARGET.[TXBHW] = SOURCE.[TXBHW]
            , TARGET.[TXBFW] = SOURCE.[TXBFW]
            , TARGET.[MWSTS] = SOURCE.[MWSTS]
            , TARGET.[WMWST] = SOURCE.[WMWST]
            , TARGET.[HWBAS] = SOURCE.[HWBAS]
            , TARGET.[FWBAS] = SOURCE.[FWBAS]
            , TARGET.[HWZUZ] = SOURCE.[HWZUZ]
            , TARGET.[FWZUZ] = SOURCE.[FWZUZ]
            , TARGET.[SHZUZ] = SOURCE.[SHZUZ]
            , TARGET.[STEKZ] = SOURCE.[STEKZ]
            , TARGET.[MWART] = SOURCE.[MWART]
            , TARGET.[TXGRP] = SOURCE.[TXGRP]
            , TARGET.[KTOSL] = SOURCE.[KTOSL]
            , TARGET.[QSSHB] = SOURCE.[QSSHB]
            , TARGET.[KURSR] = SOURCE.[KURSR]
            , TARGET.[GBETR] = SOURCE.[GBETR]
            , TARGET.[BDIFF] = SOURCE.[BDIFF]
            , TARGET.[BDIF2] = SOURCE.[BDIF2]
            , TARGET.[VALUT] = SOURCE.[VALUT]
            , TARGET.[ZUONR] = SOURCE.[ZUONR]
            , TARGET.[SGTXT] = SOURCE.[SGTXT]
            , TARGET.[ZINKZ] = SOURCE.[ZINKZ]
            , TARGET.[VBUND] = SOURCE.[VBUND]
            , TARGET.[BEWAR] = SOURCE.[BEWAR]
            , TARGET.[ALTKT] = SOURCE.[ALTKT]
            , TARGET.[VORGN] = SOURCE.[VORGN]
            , TARGET.[FDLEV] = SOURCE.[FDLEV]
            , TARGET.[FDGRP] = SOURCE.[FDGRP]
            , TARGET.[FDWBT] = SOURCE.[FDWBT]
            , TARGET.[FDTAG] = SOURCE.[FDTAG]
            , TARGET.[FKONT] = SOURCE.[FKONT]
            , TARGET.[KOKRS] = SOURCE.[KOKRS]
            , TARGET.[KOSTL] = SOURCE.[KOSTL]
            , TARGET.[PROJN] = SOURCE.[PROJN]
            , TARGET.[AUFNR] = SOURCE.[AUFNR]
            , TARGET.[VBELN] = SOURCE.[VBELN]
            , TARGET.[VBEL2] = SOURCE.[VBEL2]
            , TARGET.[POSN2] = SOURCE.[POSN2]
            , TARGET.[ETEN2] = SOURCE.[ETEN2]
            , TARGET.[ANLN1] = SOURCE.[ANLN1]
            , TARGET.[ANLN2] = SOURCE.[ANLN2]
            , TARGET.[ANBWA] = SOURCE.[ANBWA]
            , TARGET.[BZDAT] = SOURCE.[BZDAT]
            , TARGET.[PERNR] = SOURCE.[PERNR]
            , TARGET.[XUMSW] = SOURCE.[XUMSW]
            , TARGET.[XHRES] = SOURCE.[XHRES]
            , TARGET.[XKRES] = SOURCE.[XKRES]
            , TARGET.[XOPVW] = SOURCE.[XOPVW]
            , TARGET.[XCPDD] = SOURCE.[XCPDD]
            , TARGET.[XSKST] = SOURCE.[XSKST]
            , TARGET.[XSAUF] = SOURCE.[XSAUF]
            , TARGET.[XSPRO] = SOURCE.[XSPRO]
            , TARGET.[XSERG] = SOURCE.[XSERG]
            , TARGET.[XFAKT] = SOURCE.[XFAKT]
            , TARGET.[XUMAN] = SOURCE.[XUMAN]
            , TARGET.[XANET] = SOURCE.[XANET]
            , TARGET.[XSKRL] = SOURCE.[XSKRL]
            , TARGET.[XINVE] = SOURCE.[XINVE]
            , TARGET.[XPANZ] = SOURCE.[XPANZ]
            , TARGET.[XAUTO] = SOURCE.[XAUTO]
            , TARGET.[XNCOP] = SOURCE.[XNCOP]
            , TARGET.[XZAHL] = SOURCE.[XZAHL]
            , TARGET.[SAKNR] = SOURCE.[SAKNR]
            , TARGET.[HKONT] = SOURCE.[HKONT]
            , TARGET.[KUNNR] = SOURCE.[KUNNR]
            , TARGET.[LIFNR] = SOURCE.[LIFNR]
            , TARGET.[FILKD] = SOURCE.[FILKD]
            , TARGET.[XBILK] = SOURCE.[XBILK]
            , TARGET.[GVTYP] = SOURCE.[GVTYP]
            , TARGET.[HZUON] = SOURCE.[HZUON]
            , TARGET.[ZFBDT] = SOURCE.[ZFBDT]
            , TARGET.[ZTERM] = SOURCE.[ZTERM]
            , TARGET.[ZBD1T] = SOURCE.[ZBD1T]
            , TARGET.[ZBD2T] = SOURCE.[ZBD2T]
            , TARGET.[ZBD3T] = SOURCE.[ZBD3T]
            , TARGET.[ZBD1P] = SOURCE.[ZBD1P]
            , TARGET.[ZBD2P] = SOURCE.[ZBD2P]
            , TARGET.[SKFBT] = SOURCE.[SKFBT]
            , TARGET.[SKNTO] = SOURCE.[SKNTO]
            , TARGET.[WSKTO] = SOURCE.[WSKTO]
            , TARGET.[ZLSCH] = SOURCE.[ZLSCH]
            , TARGET.[ZLSPR] = SOURCE.[ZLSPR]
            , TARGET.[ZBFIX] = SOURCE.[ZBFIX]
            , TARGET.[HBKID] = SOURCE.[HBKID]
            , TARGET.[BVTYP] = SOURCE.[BVTYP]
            , TARGET.[NEBTR] = SOURCE.[NEBTR]
            , TARGET.[MWSK1] = SOURCE.[MWSK1]
            , TARGET.[DMBT1] = SOURCE.[DMBT1]
            , TARGET.[WRBT1] = SOURCE.[WRBT1]
            , TARGET.[MWSK2] = SOURCE.[MWSK2]
            , TARGET.[DMBT2] = SOURCE.[DMBT2]
            , TARGET.[WRBT2] = SOURCE.[WRBT2]
            , TARGET.[MWSK3] = SOURCE.[MWSK3]
            , TARGET.[DMBT3] = SOURCE.[DMBT3]
            , TARGET.[WRBT3] = SOURCE.[WRBT3]
            , TARGET.[REBZG] = SOURCE.[REBZG]
            , TARGET.[REBZJ] = SOURCE.[REBZJ]
            , TARGET.[REBZZ] = SOURCE.[REBZZ]
            , TARGET.[REBZT] = SOURCE.[REBZT]
            , TARGET.[ZOLLT] = SOURCE.[ZOLLT]
            , TARGET.[ZOLLD] = SOURCE.[ZOLLD]
            , TARGET.[LZBKZ] = SOURCE.[LZBKZ]
            , TARGET.[LANDL] = SOURCE.[LANDL]
            , TARGET.[DIEKZ] = SOURCE.[DIEKZ]
            , TARGET.[SAMNR] = SOURCE.[SAMNR]
            , TARGET.[ABPER] = SOURCE.[ABPER]
            , TARGET.[VRSKZ] = SOURCE.[VRSKZ]
            , TARGET.[VRSDT] = SOURCE.[VRSDT]
            , TARGET.[DISBN] = SOURCE.[DISBN]
            , TARGET.[DISBJ] = SOURCE.[DISBJ]
            , TARGET.[DISBZ] = SOURCE.[DISBZ]
            , TARGET.[WVERW] = SOURCE.[WVERW]
            , TARGET.[ANFBN] = SOURCE.[ANFBN]
            , TARGET.[ANFBJ] = SOURCE.[ANFBJ]
            , TARGET.[ANFBU] = SOURCE.[ANFBU]
            , TARGET.[ANFAE] = SOURCE.[ANFAE]
            , TARGET.[BLNBT] = SOURCE.[BLNBT]
            , TARGET.[BLNKZ] = SOURCE.[BLNKZ]
            , TARGET.[BLNPZ] = SOURCE.[BLNPZ]
            , TARGET.[MSCHL] = SOURCE.[MSCHL]
            , TARGET.[MANSP] = SOURCE.[MANSP]
            , TARGET.[MADAT] = SOURCE.[MADAT]
            , TARGET.[MANST] = SOURCE.[MANST]
            , TARGET.[MABER] = SOURCE.[MABER]
            , TARGET.[ESRNR] = SOURCE.[ESRNR]
            , TARGET.[ESRRE] = SOURCE.[ESRRE]
            , TARGET.[ESRPZ] = SOURCE.[ESRPZ]
            , TARGET.[KLIBT] = SOURCE.[KLIBT]
            , TARGET.[QSZNR] = SOURCE.[QSZNR]
            , TARGET.[QBSHB] = SOURCE.[QBSHB]
            , TARGET.[QSFBT] = SOURCE.[QSFBT]
            , TARGET.[NAVHW] = SOURCE.[NAVHW]
            , TARGET.[NAVFW] = SOURCE.[NAVFW]
            , TARGET.[MATNR] = SOURCE.[MATNR]
            , TARGET.[WERKS] = SOURCE.[WERKS]
            , TARGET.[MENGE] = SOURCE.[MENGE]
            , TARGET.[MEINS] = SOURCE.[MEINS]
            , TARGET.[ERFMG] = SOURCE.[ERFMG]
            , TARGET.[ERFME] = SOURCE.[ERFME]
            , TARGET.[BPMNG] = SOURCE.[BPMNG]
            , TARGET.[BPRME] = SOURCE.[BPRME]
            , TARGET.[EBELN] = SOURCE.[EBELN]
            , TARGET.[EBELP] = SOURCE.[EBELP]
            , TARGET.[ZEKKN] = SOURCE.[ZEKKN]
            , TARGET.[ELIKZ] = SOURCE.[ELIKZ]
            , TARGET.[VPRSV] = SOURCE.[VPRSV]
            , TARGET.[PEINH] = SOURCE.[PEINH]
            , TARGET.[BWKEY] = SOURCE.[BWKEY]
            , TARGET.[BWTAR] = SOURCE.[BWTAR]
            , TARGET.[BUSTW] = SOURCE.[BUSTW]
            , TARGET.[REWRT] = SOURCE.[REWRT]
            , TARGET.[REWWR] = SOURCE.[REWWR]
            , TARGET.[BONFB] = SOURCE.[BONFB]
            , TARGET.[BUALT] = SOURCE.[BUALT]
            , TARGET.[PSALT] = SOURCE.[PSALT]
            , TARGET.[NPREI] = SOURCE.[NPREI]
            , TARGET.[TBTKZ] = SOURCE.[TBTKZ]
            , TARGET.[SPGRP] = SOURCE.[SPGRP]
            , TARGET.[SPGRM] = SOURCE.[SPGRM]
            , TARGET.[SPGRT] = SOURCE.[SPGRT]
            , TARGET.[SPGRG] = SOURCE.[SPGRG]
            , TARGET.[SPGRV] = SOURCE.[SPGRV]
            , TARGET.[SPGRQ] = SOURCE.[SPGRQ]
            , TARGET.[STCEG] = SOURCE.[STCEG]
            , TARGET.[EGBLD] = SOURCE.[EGBLD]
            , TARGET.[EGLLD] = SOURCE.[EGLLD]
            , TARGET.[RSTGR] = SOURCE.[RSTGR]
            , TARGET.[RYACQ] = SOURCE.[RYACQ]
            , TARGET.[RPACQ] = SOURCE.[RPACQ]
            , TARGET.[RDIFF] = SOURCE.[RDIFF]
            , TARGET.[RDIF2] = SOURCE.[RDIF2]
            , TARGET.[PRCTR] = SOURCE.[PRCTR]
            , TARGET.[XHKOM] = SOURCE.[XHKOM]
            , TARGET.[VNAME] = SOURCE.[VNAME]
            , TARGET.[RECID] = SOURCE.[RECID]
            , TARGET.[EGRUP] = SOURCE.[EGRUP]
            , TARGET.[VPTNR] = SOURCE.[VPTNR]
            , TARGET.[VERTT] = SOURCE.[VERTT]
            , TARGET.[VERTN] = SOURCE.[VERTN]
            , TARGET.[VBEWA] = SOURCE.[VBEWA]
            , TARGET.[DEPOT] = SOURCE.[DEPOT]
            , TARGET.[TXJCD] = SOURCE.[TXJCD]
            , TARGET.[IMKEY] = SOURCE.[IMKEY]
            , TARGET.[DABRZ] = SOURCE.[DABRZ]
            , TARGET.[POPTS] = SOURCE.[POPTS]
            , TARGET.[FIPOS] = SOURCE.[FIPOS]
            , TARGET.[KSTRG] = SOURCE.[KSTRG]
            , TARGET.[NPLNR] = SOURCE.[NPLNR]
            , TARGET.[AUFPL] = SOURCE.[AUFPL]
            , TARGET.[APLZL] = SOURCE.[APLZL]
            , TARGET.[PROJK] = SOURCE.[PROJK]
            , TARGET.[PAOBJNR] = SOURCE.[PAOBJNR]
            , TARGET.[PASUBNR] = SOURCE.[PASUBNR]
            , TARGET.[SPGRS] = SOURCE.[SPGRS]
            , TARGET.[SPGRC] = SOURCE.[SPGRC]
            , TARGET.[BTYPE] = SOURCE.[BTYPE]
            , TARGET.[ETYPE] = SOURCE.[ETYPE]
            , TARGET.[XEGDR] = SOURCE.[XEGDR]
            , TARGET.[LNRAN] = SOURCE.[LNRAN]
            , TARGET.[HRKFT] = SOURCE.[HRKFT]
            , TARGET.[DMBE2] = SOURCE.[DMBE2]
            , TARGET.[DMBE3] = SOURCE.[DMBE3]
            , TARGET.[DMB21] = SOURCE.[DMB21]
            , TARGET.[DMB22] = SOURCE.[DMB22]
            , TARGET.[DMB23] = SOURCE.[DMB23]
            , TARGET.[DMB31] = SOURCE.[DMB31]
            , TARGET.[DMB32] = SOURCE.[DMB32]
            , TARGET.[DMB33] = SOURCE.[DMB33]
            , TARGET.[MWST2] = SOURCE.[MWST2]
            , TARGET.[MWST3] = SOURCE.[MWST3]
            , TARGET.[NAVH2] = SOURCE.[NAVH2]
            , TARGET.[NAVH3] = SOURCE.[NAVH3]
            , TARGET.[SKNT2] = SOURCE.[SKNT2]
            , TARGET.[SKNT3] = SOURCE.[SKNT3]
            , TARGET.[BDIF3] = SOURCE.[BDIF3]
            , TARGET.[RDIF3] = SOURCE.[RDIF3]
            , TARGET.[HWMET] = SOURCE.[HWMET]
            , TARGET.[GLUPM] = SOURCE.[GLUPM]
            , TARGET.[XRAGL] = SOURCE.[XRAGL]
            , TARGET.[UZAWE] = SOURCE.[UZAWE]
            , TARGET.[LOKKT] = SOURCE.[LOKKT]
            , TARGET.[FISTL] = SOURCE.[FISTL]
            , TARGET.[GEBER] = SOURCE.[GEBER]
            , TARGET.[STBUK] = SOURCE.[STBUK]
            , TARGET.[TXBH2] = SOURCE.[TXBH2]
            , TARGET.[TXBH3] = SOURCE.[TXBH3]
            , TARGET.[PPRCT] = SOURCE.[PPRCT]
            , TARGET.[XREF1] = SOURCE.[XREF1]
            , TARGET.[XREF2] = SOURCE.[XREF2]
            , TARGET.[KBLNR] = SOURCE.[KBLNR]
            , TARGET.[KBLPOS] = SOURCE.[KBLPOS]
            , TARGET.[STTAX] = SOURCE.[STTAX]
            , TARGET.[FKBER] = SOURCE.[FKBER]
            , TARGET.[OBZEI] = SOURCE.[OBZEI]
            , TARGET.[XNEGP] = SOURCE.[XNEGP]
            , TARGET.[RFZEI] = SOURCE.[RFZEI]
            , TARGET.[CCBTC] = SOURCE.[CCBTC]
            , TARGET.[KKBER] = SOURCE.[KKBER]
            , TARGET.[EMPFB] = SOURCE.[EMPFB]
            , TARGET.[XREF3] = SOURCE.[XREF3]
            , TARGET.[DTWS1] = SOURCE.[DTWS1]
            , TARGET.[DTWS2] = SOURCE.[DTWS2]
            , TARGET.[DTWS3] = SOURCE.[DTWS3]
            , TARGET.[DTWS4] = SOURCE.[DTWS4]
            , TARGET.[GRICD] = SOURCE.[GRICD]
            , TARGET.[GRIRG] = SOURCE.[GRIRG]
            , TARGET.[GITYP] = SOURCE.[GITYP]
            , TARGET.[XPYPR] = SOURCE.[XPYPR]
            , TARGET.[KIDNO] = SOURCE.[KIDNO]
            , TARGET.[ABSBT] = SOURCE.[ABSBT]
            , TARGET.[IDXSP] = SOURCE.[IDXSP]
            , TARGET.[LINFV] = SOURCE.[LINFV]
            , TARGET.[KONTT] = SOURCE.[KONTT]
            , TARGET.[KONTL] = SOURCE.[KONTL]
            , TARGET.[TXDAT] = SOURCE.[TXDAT]
            , TARGET.[AGZEI] = SOURCE.[AGZEI]
            , TARGET.[PYCUR] = SOURCE.[PYCUR]
            , TARGET.[PYAMT] = SOURCE.[PYAMT]
            , TARGET.[BUPLA] = SOURCE.[BUPLA]
            , TARGET.[SECCO] = SOURCE.[SECCO]
            , TARGET.[LSTAR] = SOURCE.[LSTAR]
            , TARGET.[CESSION_KZ] = SOURCE.[CESSION_KZ]
            , TARGET.[PRZNR] = SOURCE.[PRZNR]
            , TARGET.[PPDIFF] = SOURCE.[PPDIFF]
            , TARGET.[PPDIF2] = SOURCE.[PPDIF2]
            , TARGET.[PPDIF3] = SOURCE.[PPDIF3]
            , TARGET.[PENLC1] = SOURCE.[PENLC1]
            , TARGET.[PENLC2] = SOURCE.[PENLC2]
            , TARGET.[PENLC3] = SOURCE.[PENLC3]
            , TARGET.[PENFC] = SOURCE.[PENFC]
            , TARGET.[PENDAYS] = SOURCE.[PENDAYS]
            , TARGET.[PENRC] = SOURCE.[PENRC]
            , TARGET.[GRANT_NBR] = SOURCE.[GRANT_NBR]
            , TARGET.[SCTAX] = SOURCE.[SCTAX]
            , TARGET.[FKBER_LONG] = SOURCE.[FKBER_LONG]
            , TARGET.[GMVKZ] = SOURCE.[GMVKZ]
            , TARGET.[SRTYPE] = SOURCE.[SRTYPE]
            , TARGET.[INTRENO] = SOURCE.[INTRENO]
            , TARGET.[MEASURE] = SOURCE.[MEASURE]
            , TARGET.[AUGGJ] = SOURCE.[AUGGJ]
            , TARGET.[PPA_EX_IND] = SOURCE.[PPA_EX_IND]
            , TARGET.[DOCLN] = SOURCE.[DOCLN]
            , TARGET.[SEGMENT] = SOURCE.[SEGMENT]
            , TARGET.[PSEGMENT] = SOURCE.[PSEGMENT]
            , TARGET.[PFKBER] = SOURCE.[PFKBER]
            , TARGET.[HKTID] = SOURCE.[HKTID]
            , TARGET.[KSTAR] = SOURCE.[KSTAR]
            , TARGET.[XLGCLR] = SOURCE.[XLGCLR]
            , TARGET.[PGEBER] = SOURCE.[PGEBER]
            , TARGET.[PGRANT_NBR] = SOURCE.[PGRANT_NBR]
            , TARGET.[BUDGET_PD] = SOURCE.[BUDGET_PD]
            , TARGET.[PBUDGET_PD] = SOURCE.[PBUDGET_PD]
            , TARGET.[PEROP_BEG] = SOURCE.[PEROP_BEG]
            , TARGET.[PEROP_END] = SOURCE.[PEROP_END]
            , TARGET.[FASTPAY] = SOURCE.[FASTPAY]
            , TARGET.[PRODPER] = SOURCE.[PRODPER]
    WHEN NOT MATCHED BY TARGET THEN 
        INSERT (
            AnioMes_Id
            , CPUDT
            , AEDAT
            , [BUKRS]
            , [BELNR]
            , [GJAHR]
            , [BUZEI]
            , [BUZID]
            , [AUGDT]
            , [AUGCP]
            , [AUGBL]
            , [BSCHL]
            , [KOART]
            , [UMSKZ]
            , [UMSKS]
            , [ZUMSK]
            , [SHKZG]
            , [GSBER]
            , [PARGB]
            , [MWSKZ]
            , [QSSKZ]
            , [DMBTR]
            , [WRBTR]
            , [KZBTR]
            , [PSWBT]
            , [PSWSL]
            , [TXBHW]
            , [TXBFW]
            , [MWSTS]
            , [WMWST]
            , [HWBAS]
            , [FWBAS]
            , [HWZUZ]
            , [FWZUZ]
            , [SHZUZ]
            , [STEKZ]
            , [MWART]
            , [TXGRP]
            , [KTOSL]
            , [QSSHB]
            , [KURSR]
            , [GBETR]
            , [BDIFF]
            , [BDIF2]
            , [VALUT]
            , [ZUONR]
            , [SGTXT]
            , [ZINKZ]
            , [VBUND]
            , [BEWAR]
            , [ALTKT]
            , [VORGN]
            , [FDLEV]
            , [FDGRP]
            , [FDWBT]
            , [FDTAG]
            , [FKONT]
            , [KOKRS]
            , [KOSTL]
            , [PROJN]
            , [AUFNR]
            , [VBELN]
            , [VBEL2]
            , [POSN2]
            , [ETEN2]
            , [ANLN1]
            , [ANLN2]
            , [ANBWA]
            , [BZDAT]
            , [PERNR]
            , [XUMSW]
            , [XHRES]
            , [XKRES]
            , [XOPVW]
            , [XCPDD]
            , [XSKST]
            , [XSAUF]
            , [XSPRO]
            , [XSERG]
            , [XFAKT]
            , [XUMAN]
            , [XANET]
            , [XSKRL]
            , [XINVE]
            , [XPANZ]
            , [XAUTO]
            , [XNCOP]
            , [XZAHL]
            , [SAKNR]
            , [HKONT]
            , [KUNNR]
            , [LIFNR]
            , [FILKD]
            , [XBILK]
            , [GVTYP]
            , [HZUON]
            , [ZFBDT]
            , [ZTERM]
            , [ZBD1T]
            , [ZBD2T]
            , [ZBD3T]
            , [ZBD1P]
            , [ZBD2P]
            , [SKFBT]
            , [SKNTO]
            , [WSKTO]
            , [ZLSCH]
            , [ZLSPR]
            , [ZBFIX]
            , [HBKID]
            , [BVTYP]
            , [NEBTR]
            , [MWSK1]
            , [DMBT1]
            , [WRBT1]
            , [MWSK2]
            , [DMBT2]
            , [WRBT2]
            , [MWSK3]
            , [DMBT3]
            , [WRBT3]
            , [REBZG]
            , [REBZJ]
            , [REBZZ]
            , [REBZT]
            , [ZOLLT]
            , [ZOLLD]
            , [LZBKZ]
            , [LANDL]
            , [DIEKZ]
            , [SAMNR]
            , [ABPER]
            , [VRSKZ]
            , [VRSDT]
            , [DISBN]
            , [DISBJ]
            , [DISBZ]
            , [WVERW]
            , [ANFBN]
            , [ANFBJ]
            , [ANFBU]
            , [ANFAE]
            , [BLNBT]
            , [BLNKZ]
            , [BLNPZ]
            , [MSCHL]
            , [MANSP]
            , [MADAT]
            , [MANST]
            , [MABER]
            , [ESRNR]
            , [ESRRE]
            , [ESRPZ]
            , [KLIBT]
            , [QSZNR]
            , [QBSHB]
            , [QSFBT]
            , [NAVHW]
            , [NAVFW]
            , [MATNR]
            , [WERKS]
            , [MENGE]
            , [MEINS]
            , [ERFMG]
            , [ERFME]
            , [BPMNG]
            , [BPRME]
            , [EBELN]
            , [EBELP]
            , [ZEKKN]
            , [ELIKZ]
            , [VPRSV]
            , [PEINH]
            , [BWKEY]
            , [BWTAR]
            , [BUSTW]
            , [REWRT]
            , [REWWR]
            , [BONFB]
            , [BUALT]
            , [PSALT]
            , [NPREI]
            , [TBTKZ]
            , [SPGRP]
            , [SPGRM]
            , [SPGRT]
            , [SPGRG]
            , [SPGRV]
            , [SPGRQ]
            , [STCEG]
            , [EGBLD]
            , [EGLLD]
            , [RSTGR]
            , [RYACQ]
            , [RPACQ]
            , [RDIFF]
            , [RDIF2]
            , [PRCTR]
            , [XHKOM]
            , [VNAME]
            , [RECID]
            , [EGRUP]
            , [VPTNR]
            , [VERTT]
            , [VERTN]
            , [VBEWA]
            , [DEPOT]
            , [TXJCD]
            , [IMKEY]
            , [DABRZ]
            , [POPTS]
            , [FIPOS]
            , [KSTRG]
            , [NPLNR]
            , [AUFPL]
            , [APLZL]
            , [PROJK]
            , [PAOBJNR]
            , [PASUBNR]
            , [SPGRS]
            , [SPGRC]
            , [BTYPE]
            , [ETYPE]
            , [XEGDR]
            , [LNRAN]
            , [HRKFT]
            , [DMBE2]
            , [DMBE3]
            , [DMB21]
            , [DMB22]
            , [DMB23]
            , [DMB31]
            , [DMB32]
            , [DMB33]
            , [MWST2]
            , [MWST3]
            , [NAVH2]
            , [NAVH3]
            , [SKNT2]
            , [SKNT3]
            , [BDIF3]
            , [RDIF3]
            , [HWMET]
            , [GLUPM]
            , [XRAGL]
            , [UZAWE]
            , [LOKKT]
            , [FISTL]
            , [GEBER]
            , [STBUK]
            , [TXBH2]
            , [TXBH3]
            , [PPRCT]
            , [XREF1]
            , [XREF2]
            , [KBLNR]
            , [KBLPOS]
            , [STTAX]
            , [FKBER]
            , [OBZEI]
            , [XNEGP]
            , [RFZEI]
            , [CCBTC]
            , [KKBER]
            , [EMPFB]
            , [XREF3]
            , [DTWS1]
            , [DTWS2]
            , [DTWS3]
            , [DTWS4]
            , [GRICD]
            , [GRIRG]
            , [GITYP]
            , [XPYPR]
            , [KIDNO]
            , [ABSBT]
            , [IDXSP]
            , [LINFV]
            , [KONTT]
            , [KONTL]
            , [TXDAT]
            , [AGZEI]
            , [PYCUR]
            , [PYAMT]
            , [BUPLA]
            , [SECCO]
            , [LSTAR]
            , [CESSION_KZ]
            , [PRZNR]
            , [PPDIFF]
            , [PPDIF2]
            , [PPDIF3]
            , [PENLC1]
            , [PENLC2]
            , [PENLC3]
            , [PENFC]
            , [PENDAYS]
            , [PENRC]
            , [GRANT_NBR]
            , [SCTAX]
            , [FKBER_LONG]
            , [GMVKZ]
            , [SRTYPE]
            , [INTRENO]
            , [MEASURE]
            , [AUGGJ]
            , [PPA_EX_IND]
            , [DOCLN]
            , [SEGMENT]
            , [PSEGMENT]
            , [PFKBER]
            , [HKTID]
            , [KSTAR]
            , [XLGCLR]
            , [PGEBER]
            , [PGRANT_NBR]
            , [BUDGET_PD]
            , [PBUDGET_PD]
            , [PEROP_BEG]
            , [PEROP_END]
            , [FASTPAY]
            , [PRODPER]
        )		
        VALUES (
            SOURCE.AnioMes_Id
            , SOURCE.CPUDT
            , SOURCE.AEDAT
            , SOURCE.[BUKRS]
            , SOURCE.[BELNR]
            , SOURCE.[GJAHR]
            , SOURCE.[BUZEI]
            , SOURCE.[BUZID]
            , SOURCE.[AUGDT]
            , SOURCE.[AUGCP]
            , SOURCE.[AUGBL]
            , SOURCE.[BSCHL]
            , SOURCE.[KOART]
            , SOURCE.[UMSKZ]
            , SOURCE.[UMSKS]
            , SOURCE.[ZUMSK]
            , SOURCE.[SHKZG]
            , SOURCE.[GSBER]
            , SOURCE.[PARGB]
            , SOURCE.[MWSKZ]
            , SOURCE.[QSSKZ]
            , SOURCE.[DMBTR]
            , SOURCE.[WRBTR]
            , SOURCE.[KZBTR]
            , SOURCE.[PSWBT]
            , SOURCE.[PSWSL]
            , SOURCE.[TXBHW]
            , SOURCE.[TXBFW]
            , SOURCE.[MWSTS]
            , SOURCE.[WMWST]
            , SOURCE.[HWBAS]
            , SOURCE.[FWBAS]
            , SOURCE.[HWZUZ]
            , SOURCE.[FWZUZ]
            , SOURCE.[SHZUZ]
            , SOURCE.[STEKZ]
            , SOURCE.[MWART]
            , SOURCE.[TXGRP]
            , SOURCE.[KTOSL]
            , SOURCE.[QSSHB]
            , SOURCE.[KURSR]
            , SOURCE.[GBETR]
            , SOURCE.[BDIFF]
            , SOURCE.[BDIF2]
            , SOURCE.[VALUT]
            , SOURCE.[ZUONR]
            , SOURCE.[SGTXT]
            , SOURCE.[ZINKZ]
            , SOURCE.[VBUND]
            , SOURCE.[BEWAR]
            , SOURCE.[ALTKT]
            , SOURCE.[VORGN]
            , SOURCE.[FDLEV]
            , SOURCE.[FDGRP]
            , SOURCE.[FDWBT]
            , SOURCE.[FDTAG]
            , SOURCE.[FKONT]
            , SOURCE.[KOKRS]
            , SOURCE.[KOSTL]
            , SOURCE.[PROJN]
            , SOURCE.[AUFNR]
            , SOURCE.[VBELN]
            , SOURCE.[VBEL2]
            , SOURCE.[POSN2]
            , SOURCE.[ETEN2]
            , SOURCE.[ANLN1]
            , SOURCE.[ANLN2]
            , SOURCE.[ANBWA]
            , SOURCE.[BZDAT]
            , SOURCE.[PERNR]
            , SOURCE.[XUMSW]
            , SOURCE.[XHRES]
            , SOURCE.[XKRES]
            , SOURCE.[XOPVW]
            , SOURCE.[XCPDD]
            , SOURCE.[XSKST]
            , SOURCE.[XSAUF]
            , SOURCE.[XSPRO]
            , SOURCE.[XSERG]
            , SOURCE.[XFAKT]
            , SOURCE.[XUMAN]
            , SOURCE.[XANET]
            , SOURCE.[XSKRL]
            , SOURCE.[XINVE]
            , SOURCE.[XPANZ]
            , SOURCE.[XAUTO]
            , SOURCE.[XNCOP]
            , SOURCE.[XZAHL]
            , SOURCE.[SAKNR]
            , SOURCE.[HKONT]
            , SOURCE.[KUNNR]
            , SOURCE.[LIFNR]
            , SOURCE.[FILKD]
            , SOURCE.[XBILK]
            , SOURCE.[GVTYP]
            , SOURCE.[HZUON]
            , SOURCE.[ZFBDT]
            , SOURCE.[ZTERM]
            , SOURCE.[ZBD1T]
            , SOURCE.[ZBD2T]
            , SOURCE.[ZBD3T]
            , SOURCE.[ZBD1P]
            , SOURCE.[ZBD2P]
            , SOURCE.[SKFBT]
            , SOURCE.[SKNTO]
            , SOURCE.[WSKTO]
            , SOURCE.[ZLSCH]
            , SOURCE.[ZLSPR]
            , SOURCE.[ZBFIX]
            , SOURCE.[HBKID]
            , SOURCE.[BVTYP]
            , SOURCE.[NEBTR]
            , SOURCE.[MWSK1]
            , SOURCE.[DMBT1]
            , SOURCE.[WRBT1]
            , SOURCE.[MWSK2]
            , SOURCE.[DMBT2]
            , SOURCE.[WRBT2]
            , SOURCE.[MWSK3]
            , SOURCE.[DMBT3]
            , SOURCE.[WRBT3]
            , SOURCE.[REBZG]
            , SOURCE.[REBZJ]
            , SOURCE.[REBZZ]
            , SOURCE.[REBZT]
            , SOURCE.[ZOLLT]
            , SOURCE.[ZOLLD]
            , SOURCE.[LZBKZ]
            , SOURCE.[LANDL]
            , SOURCE.[DIEKZ]
            , SOURCE.[SAMNR]
            , SOURCE.[ABPER]
            , SOURCE.[VRSKZ]
            , SOURCE.[VRSDT]
            , SOURCE.[DISBN]
            , SOURCE.[DISBJ]
            , SOURCE.[DISBZ]
            , SOURCE.[WVERW]
            , SOURCE.[ANFBN]
            , SOURCE.[ANFBJ]
            , SOURCE.[ANFBU]
            , SOURCE.[ANFAE]
            , SOURCE.[BLNBT]
            , SOURCE.[BLNKZ]
            , SOURCE.[BLNPZ]
            , SOURCE.[MSCHL]
            , SOURCE.[MANSP]
            , SOURCE.[MADAT]
            , SOURCE.[MANST]
            , SOURCE.[MABER]
            , SOURCE.[ESRNR]
            , SOURCE.[ESRRE]
            , SOURCE.[ESRPZ]
            , SOURCE.[KLIBT]
            , SOURCE.[QSZNR]
            , SOURCE.[QBSHB]
            , SOURCE.[QSFBT]
            , SOURCE.[NAVHW]
            , SOURCE.[NAVFW]
            , SOURCE.[MATNR]
            , SOURCE.[WERKS]
            , SOURCE.[MENGE]
            , SOURCE.[MEINS]
            , SOURCE.[ERFMG]
            , SOURCE.[ERFME]
            , SOURCE.[BPMNG]
            , SOURCE.[BPRME]
            , SOURCE.[EBELN]
            , SOURCE.[EBELP]
            , SOURCE.[ZEKKN]
            , SOURCE.[ELIKZ]
            , SOURCE.[VPRSV]
            , SOURCE.[PEINH]
            , SOURCE.[BWKEY]
            , SOURCE.[BWTAR]
            , SOURCE.[BUSTW]
            , SOURCE.[REWRT]
            , SOURCE.[REWWR]
            , SOURCE.[BONFB]
            , SOURCE.[BUALT]
            , SOURCE.[PSALT]
            , SOURCE.[NPREI]
            , SOURCE.[TBTKZ]
            , SOURCE.[SPGRP]
            , SOURCE.[SPGRM]
            , SOURCE.[SPGRT]
            , SOURCE.[SPGRG]
            , SOURCE.[SPGRV]
            , SOURCE.[SPGRQ]
            , SOURCE.[STCEG]
            , SOURCE.[EGBLD]
            , SOURCE.[EGLLD]
            , SOURCE.[RSTGR]
            , SOURCE.[RYACQ]
            , SOURCE.[RPACQ]
            , SOURCE.[RDIFF]
            , SOURCE.[RDIF2]
            , SOURCE.[PRCTR]
            , SOURCE.[XHKOM]
            , SOURCE.[VNAME]
            , SOURCE.[RECID]
            , SOURCE.[EGRUP]
            , SOURCE.[VPTNR]
            , SOURCE.[VERTT]
            , SOURCE.[VERTN]
            , SOURCE.[VBEWA]
            , SOURCE.[DEPOT]
            , SOURCE.[TXJCD]
            , SOURCE.[IMKEY]
            , SOURCE.[DABRZ]
            , SOURCE.[POPTS]
            , SOURCE.[FIPOS]
            , SOURCE.[KSTRG]
            , SOURCE.[NPLNR]
            , SOURCE.[AUFPL]
            , SOURCE.[APLZL]
            , SOURCE.[PROJK]
            , SOURCE.[PAOBJNR]
            , SOURCE.[PASUBNR]
            , SOURCE.[SPGRS]
            , SOURCE.[SPGRC]
            , SOURCE.[BTYPE]
            , SOURCE.[ETYPE]
            , SOURCE.[XEGDR]
            , SOURCE.[LNRAN]
            , SOURCE.[HRKFT]
            , SOURCE.[DMBE2]
            , SOURCE.[DMBE3]
            , SOURCE.[DMB21]
            , SOURCE.[DMB22]
            , SOURCE.[DMB23]
            , SOURCE.[DMB31]
            , SOURCE.[DMB32]
            , SOURCE.[DMB33]
            , SOURCE.[MWST2]
            , SOURCE.[MWST3]
            , SOURCE.[NAVH2]
            , SOURCE.[NAVH3]
            , SOURCE.[SKNT2]
            , SOURCE.[SKNT3]
            , SOURCE.[BDIF3]
            , SOURCE.[RDIF3]
            , SOURCE.[HWMET]
            , SOURCE.[GLUPM]
            , SOURCE.[XRAGL]
            , SOURCE.[UZAWE]
            , SOURCE.[LOKKT]
            , SOURCE.[FISTL]
            , SOURCE.[GEBER]
            , SOURCE.[STBUK]
            , SOURCE.[TXBH2]
            , SOURCE.[TXBH3]
            , SOURCE.[PPRCT]
            , SOURCE.[XREF1]
            , SOURCE.[XREF2]
            , SOURCE.[KBLNR]
            , SOURCE.[KBLPOS]
            , SOURCE.[STTAX]
            , SOURCE.[FKBER]
            , SOURCE.[OBZEI]
            , SOURCE.[XNEGP]
            , SOURCE.[RFZEI]
            , SOURCE.[CCBTC]
            , SOURCE.[KKBER]
            , SOURCE.[EMPFB]
            , SOURCE.[XREF3]
            , SOURCE.[DTWS1]
            , SOURCE.[DTWS2]
            , SOURCE.[DTWS3]
            , SOURCE.[DTWS4]
            , SOURCE.[GRICD]
            , SOURCE.[GRIRG]
            , SOURCE.[GITYP]
            , SOURCE.[XPYPR]
            , SOURCE.[KIDNO]
            , SOURCE.[ABSBT]
            , SOURCE.[IDXSP]
            , SOURCE.[LINFV]
            , SOURCE.[KONTT]
            , SOURCE.[KONTL]
            , SOURCE.[TXDAT]
            , SOURCE.[AGZEI]
            , SOURCE.[PYCUR]
            , SOURCE.[PYAMT]
            , SOURCE.[BUPLA]
            , SOURCE.[SECCO]
            , SOURCE.[LSTAR]
            , SOURCE.[CESSION_KZ]
            , SOURCE.[PRZNR]
            , SOURCE.[PPDIFF]
            , SOURCE.[PPDIF2]
            , SOURCE.[PPDIF3]
            , SOURCE.[PENLC1]
            , SOURCE.[PENLC2]
            , SOURCE.[PENLC3]
            , SOURCE.[PENFC]
            , SOURCE.[PENDAYS]
            , SOURCE.[PENRC]
            , SOURCE.[GRANT_NBR]
            , SOURCE.[SCTAX]
            , SOURCE.[FKBER_LONG]
            , SOURCE.[GMVKZ]
            , SOURCE.[SRTYPE]
            , SOURCE.[INTRENO]
            , SOURCE.[MEASURE]
            , SOURCE.[AUGGJ]
            , SOURCE.[PPA_EX_IND]
            , SOURCE.[DOCLN]
            , SOURCE.[SEGMENT]
            , SOURCE.[PSEGMENT]
            , SOURCE.[PFKBER]
            , SOURCE.[HKTID]
            , SOURCE.[KSTAR]
            , SOURCE.[XLGCLR]
            , SOURCE.[PGEBER]
            , SOURCE.[PGRANT_NBR]
            , SOURCE.[BUDGET_PD]
            , SOURCE.[PBUDGET_PD]
            , SOURCE.[PEROP_BEG]
            , SOURCE.[PEROP_END]
            , SOURCE.[FASTPAY]
            , SOURCE.[PRODPER]
            )
    ;
    SET @Filas = @@ROWCOUNT
    COMMIT TRANSACTION

    DROP TABLE IF EXISTS #DL_SAP_BSEG_TEMP4578621

    SET @Duracion_Minutos = ROUND(DATEDIFF(SECOND, @TiempoInicio, GETDATE()) * 1.0 / 60, 4)
    SET @sql = CONCAT('DL_paCargarSAP_Replica_BSEG', ' Filas: ', @Filas, ' IndicadorActualizarTodo = ', @p_IndicadorActualizarTodo, ' Desde: ', @fechaInicioSAP)
    EXEC DL_FARINTER.[dbo].DL_paEscBitacora
        @Mensaje = @sql, @Tipo = 'Finalizado', @Tabla = 'DL_SAP_BSEG', @DuracionMinutos = @Duracion_Minutos


END try
BEGIN catch
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
    SET @Duracion_Minutos = ROUND(DATEDIFF(SECOND, @TiempoInicio, GETDATE()) * 1.0 / 60, 4)
    SET @sql = CONCAT('DL_paCargarSAP_Replica_BSEG' , ERROR_MESSAGE(), ' IndicadorActualizarTodo = ', @p_IndicadorActualizarTodo)
    EXEC DL_FARINTER.[dbo].DL_paEscBitacora
        @Mensaje = @sql, @Tipo = 'Error', @Tabla = 'DL_SAP_BSEG', @DuracionMinutos = @Duracion_Minutos
        ;
    THROW;
END catch

-- #### Espacio de Pruebas
/*
EXEC [DL_FARINTER].[dbo].[DL_paCargarSAP_Replica_BSEG] --@p_IndicadorActualizarTodo = 1

SELECT TOP 100 * FROM DL_FARINTER.dbo.DL_CnfBitacora WHERE Bitacora_Tabla = 'DL_SAP_BSEG' ORDER BY Bitacora_Fecha DESC
SELECT TOP 100 * FROM DL_FARINTER.dbo.DL_SAP_BSEG A


*/

