sources:
  - name: BI_FARINTER
    description: "Base de DL"
    database: BI_FARINTER
    schema: dbo
    tables:
      - name: BI_SAP_Hecho_Facturas_Posiciones_Reciente
      - name: BI_SAP_Hecho_Facturas_Posiciones_Actual
      - name: BI_SAP_Dim_Facturas_Reciente
      - name: BI_SAP_Dim_Facturas_Actual
      - name: BI_SAP_Dim_Cliente
