
version: 3

models:
  - name: BI_SAP_Dim_Sociedad
    description: "A starter dbt model"
    columns:
      - name: Sociedad_Id
        description: "Sociedad o Empresa Individual"
        tests:
          - unique
          - not_null
